### ISSUE TITLE
Create test to verify that builds for iOS and Android succeed

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1213]
This will likely require some painful debugging, but a good goal would be to do a Meteor build for iOS and Android architecture without error.

**Comment by 3Maestros** [comment]
This is the error I see when I do "meteor run android" .

##########
shell.js: internal errorugins                /                                     
Error: ENOENT, no such file or directory '/Users/Aquaboi/work-space/meteor/reaction/.meteor/local/cordova-build/www/*'
    at Object.fs.statSync (fs.js:696:18)
    at /Users/Aquaboi/work-space/meteor/reaction/node_modules/shelljs/src/cp.js:148:21
    at Array.forEach (native)
    at Object._cp (/Users/Aquaboi/work-space/meteor/reaction/node_modules/shelljs/src/cp.js:144:13)
    at Object.cp (/Users/Aquaboi/work-space/meteor/reaction/node_modules/shelljs/src/common.js:240:23)
##########

**Comment by 3Maestros** [comment]
@Capt-Slow 
I have gone past this error by doing "m -rf .meteor/local/cordova-build/" from your project directory. Now the app gets installed but see following error on start up in console .
############
TypeError: Cannot read property 'language' of undefined
    at http://localhost:12760/app/app.js?hash=5e2d9a4f04e382a0caa6863efa24d2779ab056ad:33898:28
    at http://localhost:12760/app/app.js?hash=5e2d9a4f04e382a0caa6863efa24d2779ab056ad:33966:8
    at Tracker.Computation._compute (http://localhost:12760/packages/tracker.js?hash=f525263111eb9d90f4ce1ad064f97aca4a6c1b07:339:36)
    at Tracker.Computation._recompute (http://localhost:12760/packages/tracker.js?hash=f525263111eb9d90f4ce1ad064f97aca4a6c1b07:358:14)
    at Object.Tracker._runFlush (http://localhost:12760/packages/tracker.js?hash=f525263111eb9d90f4ce1ad064f97aca4a6c1b07:523:14)
    at onGlobalMessage (http://localhost:12760/packages/meteor.js?hash=0b0ea1099ba8153bbbc5fb555a755bdff3cec0c3:429:23)
##################
This is at line client/module/i18n/startup.js line 43, not sure why it is not able to read the property.
I was able to read shops collection from chrome://inspect/#devices console, not sure why the mobile app is not able to read the property.

**Comment by zenweasel** [comment]
Closing this as mobile apps are not on the current roadmap
