### ISSUE TITLE
Startup Import does not check against schema

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1226]
### Expected behavior

Only valid records should be imported
### Actual Behavior

Records which fail a validation check are imported and then fail when they are used.
### Steps to Reproduce the Behavior

Modify `Products.json` so that a Product record is missing key fields, Import will import them but then fail the first time they are used.

**Comment by zenweasel** [comment]
We saw that this also happens with `Packages`. @impactmass tried to write a migration to update Packages but could not reinsert the record because the current records don't match `[Layout]` schema.

**Comment by zenweasel** [comment]
The error message is not completely clear but it does appear to get validated on startup:

```
06:46:36.972Z ERROR Reaction: Bypassing loading Products default data.
  TypeError: Cannot read property 'clean' of null
      at Object._Import.object (server/api/core/import.js:416:3)
      at Object._Import.product (server/api/core/import.js:253:15)
      at Object._Import.process (server/api/core/import.js:471:14)
```
Checked on the `node-simple-schema` branch and error message is the same
