### ISSUE TITLE
report misconfigured smtp in dashboard.

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1318]
### Expected behavior

- Save SMTP settings, issue with settings, be notified credentials don't work.  (validate/HELO on save)

- Save SMTP settings, send email, no issues.

### Actual Behavior
```
I20160821-17:27:37.111(-7)?       at Object.Future.wait (/Users/aaronjudd/.meteor/packages/meteor-tool/.1.4.1.l6jtqd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
I20160821-17:27:37.112(-7)?       at smtpSend (packages/email/email.js:89:1)
I20160821-17:27:37.112(-7)?       at Object.Email.send (packages/email/email.js:192:1)
I20160821-17:27:37.112(-7)?       at server/jobs/email.js:32:15
I20160821-17:27:37.113(-7)?       at Array.forEach (native)
I20160821-17:27:37.113(-7)?       at JobQueue.worker (server/jobs/email.js:18:10)
I20160821-17:27:37.114(-7)?       at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:191:8)
I20160821-17:27:37.114(-7)?       at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160821-17:27:37.114(-7)?       at packages/meteor/timers.js:6:1
I20160821-17:27:37.115(-7)?       at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160821-17:27:37.115(-7)?       - - - - -
I20160821-17:27:37.115(-7)?       at Object.exports._errnoException (util.js:907:11)
I20160821-17:27:37.116(-7)?       at exports._exceptionWithHostPort (util.js:930:20)
I20160821-17:27:37.116(-7)?       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)
W20160821-17:27:37.126(-7)? (STDERR) Running job not found 35bd9Xws47GdcJ8Ms fmuZpdg8X6JCefNLo
```
### Steps to Reproduce the Behavior
Save misconfigured email settings, send an email (register a new user, order update,etc). watch server console, when email send timeout.

**Comment by jshimko** [comment]
I spent half my day with this issue today and I'm in the process of improving the situation.  Assigned myself.  Details to follow...
