### ISSUE TITLE
Server error when cloning product

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1319]
### Expected behavior

No error when cloning product
### Actual Behavior

Receive error in both the server and client console: Traceback from server console:

```
I20160823-13:55:28.094(8)? Exception while invoking method 'products/cloneProduct' TypeError: Cannot read property 'newId' of undefined
I20160823-13:55:28.095(8)?     at server/methods/catalog.js:580:27
I20160823-13:55:28.095(8)?     at Array.map (native)
I20160823-13:55:28.095(8)?     at buildAncestors (server/methods/catalog.js:577:17)
I20160823-13:55:28.095(8)?     at [object Object].productsCloneProduct (server/methods/catalog.js:637:27)
I20160823-13:55:28.096(8)?     at packages/check/match.js:107:1
I20160823-13:55:28.096(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160823-13:55:28.096(8)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
I20160823-13:55:28.097(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
I20160823-13:55:28.097(8)?     at packages/ddp-server/livedata_server.js:711:19
I20160823-13:55:28.097(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160823-13:55:28.097(8)?     at packages/ddp-server/livedata_server.js:709:40
I20160823-13:55:28.097(8)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160823-13:55:28.098(8)?     at packages/ddp-server/livedata_server.js:707:46
I20160823-13:55:28.098(8)?     at Session.method (packages/ddp-server/livedata_server.js:681:23)
I20160823-13:55:28.099(8)?     at packages/ddp-server/livedata_server.js:551:43
```
### Steps to Reproduce the Behavior
1. Create a new product from scratch
2. Try to clone it from side menu
3. Observe the error.
4. Clone seems to be successful except variants are not cloned

**Comment by zenweasel** [comment]
@mikemurray Was "clone a product" functionality removed, or I am just stupid and missing it?

**Comment by mikemurray** [comment]
You can only clone the top level products from the product grid. You used to be able to clone them from the product detail page, but I think that got lost in my updates / revision control and stuff in 0.17.

**Comment by mikemurray** [comment]
Looks like the product and the variants do get copied, but the media does not.

**Comment by zenweasel** [comment]
@mikemurray Shouldn't we reinstate product cloning? This seems like a pretty core feature to lose?

**Comment by zenweasel** [comment]
You can clone from the "edit" sidebar in the product grid, and that works without error. Closing.
