### ISSUE TITLE
search related order workflow error

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1454]
In `development` branch, attempting to approve payment (order fulfillment workflow), search causes an exception:

```
I20160930-08:56:31.353(-7)? Exception while invoking method 'workflow/pushOrderWorkflow' TypeError: Cannot read property 'emails' of undefined
I20160930-08:56:31.353(-7)?     at buildOrderSearchRecord (imports/plugins/included/search-mongo/server/methods/searchcollections.js:170:23)
I20160930-08:56:31.354(-7)?     at Object.<anonymous> (imports/plugins/included/search-mongo/server/hooks/search.js:46:5)
I20160930-08:56:31.354(-7)?     at packages/matb33_collection-hooks/update.js:70:1
I20160930-08:56:31.354(-7)?     at Array.forEach (native)
I20160930-08:56:31.354(-7)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160930-08:56:31.355(-7)?     at packages/matb33_collection-hooks/update.js:69:1
I20160930-08:56:31.355(-7)?     at Array.forEach (native)
I20160930-08:56:31.355(-7)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160930-08:56:31.356(-7)?     at after (packages/matb33_collection-hooks/update.js:68:1)
I20160930-08:56:31.356(-7)?     at Object.<anonymous> (packages/matb33_collection-hooks/update.js:89:1)
I20160930-08:56:31.359(-7)?     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:120:1)
I20160930-08:56:31.359(-7)?     at [object Object].update (packages/mongo/collection.js:589:29)
I20160930-08:56:31.360(-7)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:203:1)
I20160930-08:56:31.360(-7)?     at [object Object].workflowPushOrderWorkflow (imports/plugins/core/checkout/server/methods/workflow.js:271:27)
I20160930-08:56:31.361(-7)?     at packages/check/match.js:107:1
I20160930-08:56:31.361(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160930-08:56:31.362(-7)?     at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
I20160930-08:56:31.363(-7)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
I20160930-08:56:31.363(-7)?     at packages/ddp-server/livedata_server.js:711:19
I20160930-08:56:31.364(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160930-08:56:31.364(-7)?     at packages/ddp-server/livedata_server.js:709:40
I20160930-08:56:31.364(-7)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160930-08:56:33.506(-7)? Exception while invoking method 'orders/approvePayment' TypeError: Cannot read property 'emails' of undefined
I20160930-08:56:33.507(-7)?     at buildOrderSearchRecord (imports/plugins/included/search-mongo/server/methods/searchcollections.js:170:23)
I20160930-08:56:33.507(-7)?     at Object.<anonymous> (imports/plugins/included/search-mongo/server/hooks/search.js:46:5)
I20160930-08:56:33.507(-7)?     at packages/matb33_collection-hooks/update.js:70:1
I20160930-08:56:33.507(-7)?     at Array.forEach (native)
I20160930-08:56:33.508(-7)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160930-08:56:33.508(-7)?     at packages/matb33_collection-hooks/update.js:69:1
I20160930-08:56:33.509(-7)?     at Array.forEach (native)
I20160930-08:56:33.509(-7)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20160930-08:56:33.509(-7)?     at after (packages/matb33_collection-hooks/update.js:68:1)
I20160930-08:56:33.509(-7)?     at Object.<anonymous> (packages/matb33_collection-hooks/update.js:89:1)
I20160930-08:56:33.509(-7)?     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:120:1)
I20160930-08:56:33.510(-7)?     at [object Object].update (packages/mongo/collection.js:589:29)
I20160930-08:56:33.510(-7)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:203:1)
```

**Comment by zenweasel** [comment]
Closed via #1460
