### ISSUE TITLE
[PDP] Receive error when editing variant

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1482]
I feel like this may have just been introduced recently
### Expected behavior

You should be able to edit a variant without receiving an error
### Actual Behavior

Receive the following error in the server console:

```
I20161007-08:05:13.095(8)? Exception in queued task: Error: Could not find element with id CJoRBm9vRrorc9mxZ to change
I20161007-08:05:13.097(8)?     at SessionCollectionView.changed (packages/ddp-server/livedata_server.js:188:13)
I20161007-08:05:13.097(8)?     at Session.changed (packages/ddp-server/livedata_server.js:400:10)
I20161007-08:05:13.098(8)?     at Subscription.changed (packages/ddp-server/livedata_server.js:1253:19)
I20161007-08:05:13.099(8)?     at changed (server/publications/collections/products.js:288:20)
I20161007-08:05:13.099(8)?     at packages/mongo/observe_multiplex.js:183:30
I20161007-08:05:13.099(8)?     at Array.forEach (native)
I20161007-08:05:13.100(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20161007-08:05:13.101(8)?     at Object.task (packages/mongo/observe_multiplex.js:177:9)
I20161007-08:05:13.101(8)?     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
I20161007-08:05:13.102(8)?     at packages/meteor/fiber_helpers.js:125:1
```
### Steps to Reproduce the Behavior
1. Login as administrator
2. Go to product detail page
3. Click on pencil to edit a variant
4. Change option name and click out
5. Observe error in server console.
6. Observe values does not change in main screen

**Comment by zenweasel** [comment]
Can't reproduce in `release-0.18.0`
