### ISSUE TITLE
Upgrading 0.15 -> 0.17 throws type error

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#1524]
### Actual Behavior

Here's the error

```
Exception in setTimeout callback: TypeError: Cannot read property 'fullName' of undefined
    at Object.transformations.accounts.profile (imports/plugins/included/search-mongo/server/methods/transformations.js:31:45)
    at buildAccountSearch (imports/plugins/included/search-mongo/server/methods/searchcollections.js:212:32)
    at JobQueue.worker (imports/plugins/included/search-mongo/server/jobs/buildSearchCollections.js:145:7)
    at JobQueue._process (packages/vsivsi_job-collection/job/src/job_class.coffee:191:8)
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/meteor/timers.js:6:1
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
```
### Steps to Reproduce the Behavior

Upgraded existing shop with data to `reaction:master` 0.17

PR incoming.

**Comment by zenweasel** [comment]
Did the migrations run? Because preventing that error was basically why that was written

**Comment by spencern** [comment]
It said that the migrations ran, but I think what happened is that there was an empty address book (`addressBook === []`) in the `transformations.js` file.
