### ISSUE TITLE
App is not starting on windows 7 and showing the following error ? Installed all the dependencies as mentioned in Installation instructions.

### ISSUE THREAD

**Issue by jindalhackerrank** [reactioncommerce/reaction#1589]
=> A patch (Meteor 1.4.2.3) for your current release is available!
   Update this project now with 'meteor update --patch'.
Started MongoDB.
Errors prevented startup:

```
While loading package momentjs:moment@2.15.2:
error: Command failed: C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\bin\npm.cmd rebuild --update-binary
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-win32-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\python\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-1pvbkz9\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32\\fse.node" "--module_name=fse" "--module_path=C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-1pvbkz9\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32"
gyp ERR! cwd C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\bin\node.exe C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32\fse.node --module_name=fse --module_path=C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents
node-pre-gyp ERR! node -v v4.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--update-binary"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\npm-debug.log
node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-win32-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@4.6.1 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\python\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\polyfills.js:264:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-1pvbkz9\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32\\fse.node" "--module_name=fse" "--module_path=C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\momentjs_moment\\2.15.2\\npm\\node_modules\\.temp-1pvbkz9\\node_modules\\fsevents\\lib\\binding\\Release\\node-v46-win32-ia32"
gyp ERR! cwd C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\bin\node.exe C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32\fse.node --module_name=fse --module_path=C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents\lib\binding\Release\node-v46-win32-ia32' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\ajind7\AppData\Local\.meteor\packages\meteor-tool\1.4.2\mt-os.windows.x86_32\dev_bundle\lib\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\node_modules\fsevents
node-pre-gyp ERR! node -v v4.6.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\ajind7\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--update-binary"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\ajind7\AppData\Local\.meteor\packages\momentjs_moment\2.15.2\npm\node_modules\.temp-1pvbkz9\npm-debug.log


Your application has errors. Waiting for file change.
```

**Comment by hrath2015** [comment]
Please do a build from Dev branch . `` reaction init -b development``

**Comment by zenweasel** [comment]
Fixed in development
