### ISSUE TITLE
Receive error in server console when creating product

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#1646]
### Expected behavior
No error

### Actual Behavior
Receive the following error in the server console. The error keeps repeating
```
Exception in queued task: Error: Could not find element with id 6Drb6GEaAdtnCjiKj to change
    at SessionCollectionView.changed (packages/ddp-server/livedata_server.js:188:13)
    at Session.changed (packages/ddp-server/livedata_server.js:400:10)
    at Subscription.changed (packages/ddp-server/livedata_server.js:1254:19)
    at Object.removed (server/publications/collections/product.js:137:18)
    at [object Object].observeChangesCallbacks.removed (packages/minimongo.js:3802:28)
    at self.applyChange.removed (packages/minimongo.js:3704:44)
    at packages/mongo/observe_multiplex.js:183:30
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:177:9)
    at [object Object]._.extend._run (packages/meteor.js:807:18)
    at packages/meteor.js:785:14
```

### Steps to Reproduce the Behavior
You have to follow these steps very specifically in order.

1. Create a new product
1. Edit the variant, setting the quantity, price etc.
1. Click the eye icon in the bottom right to make the product visible. (not the variant)
1. Publish (the product has no price because the variant was not published)
1. Click the eye icon next to the variant
1. Observe the error in the console.
1. Observe that you can never publish the variant,

I was able to replicate this three times in a row on the `release-0.18.0` using the above instructions.

**Comment by mikemurray** [comment]
This appears to be resolved in development, but leaving open for now to verify after using it for a while.
