### ISSUE TITLE
Installation - file table overflow

### ISSUE THREAD

**Issue by iGitScor** [reactioncommerce/reaction#1890]
Hi folks,

thank you for the great work.
I've tried to reinstall reaction (I installed it few months ago) but after following install steps I've got an issue.

### Expected behavior

Run the reaction framework

### Actual Behavior

```sh
Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~/Documents/dev/shop ]]]]]

=> Started proxy.
=> A patch (Meteor 1.4.2.7) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.
/Users/username/.meteor/packages/coffeescript/.1.11.1_4.1jq3ymo++os+web.browser+web.cordova/plugin.compileCoffeescript.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

Error: ENFILE: file table overflow, scandir '/Users/username/Documents/dev/shop/packages/gridfs'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.wrapper (/tools/fs/files.js:1535:35)
    at readDirectory (/Users/username/.meteor/packages/meteor-tool/.1.4.2_3.6vwv24++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:291:26)
    at Watcher._fireIfDirectoryChanged (/Users/username/.meteor/packages/meteor-tool/.1.4.2_3.6vwv24++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:436:23)
    at /Users/username/.meteor/packages/meteor-tool/.1.4.2_3.6vwv24++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:682:12
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/username/.meteor/packages/meteor-tool/.1.4.2_3.6vwv24++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at Watcher._checkDirectories (/Users/username/.meteor/packages/meteor-tool/.1.4.2_3.6vwv24++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:671:7)
    at new Watcher (/Users/username/.meteor/packages/meteor-tool/.1.4.2_3.6vwv24++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/tools/fs/watch.js:385:10)
    at setupClientWatcher (/tools/runners/run-app.js:786:23)
    at AppRunner._runOnce (/tools/runners/run-app.js:797:7)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12
```

### Steps to Reproduce the Behavior

* I installed **reaction-cli**
* I launched the following commands:

```sh
npm install -g reaction-cli
reaction init shop
cd shop
reaction
```
npm packages were updated, then I get the previous stack trace error.
I've tried to run `reaction pull` then `reaction run` and I got the same issue.
I've also tried to launch `meteor`, same result.

### Configuration

- Node v6.1.0
- npm v4.2.0
- Mac OS Sierra 10.12.2

Do you need more information ?

Thank you

**Comment by aaronjudd** [comment]
This looks related to https://github.com/reactioncommerce/reaction/issues/1590 as well as the related meteor issue https://github.com/meteor/meteor/issues/8002

Short story, increasing your OS X file limits should help:


```
$ echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
$ echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf
$ sudo sysctl -w kern.maxfiles=65536
$ sudo sysctl -w kern.maxfilesperproc=65536
$ ulimit -n 65536
```

**Comment by iGitScor** [comment]
Thank you @aaronjudd 

I would like to know the impact to the environnement, is it sure ?
I don't like modify OS configuration for development. I do not feel comfortable with this idea

**Comment by aaronjudd** [comment]
Looks like you are also running an older version of meteor, and probably reaction.  Meteor has resolved many of the file issues in 1.4.2.7, which we are running in development branch, and which will be released to master today. This should help, but generally this is a documented issue (actually there's a of related lot of issues) in the Meteor project, and while I agree with you about modifying the dev env, this is a suggested workaround.

**Comment by jshimko** [comment]
@iGitScor all you're modifying is the amount of open files the OS will allow.  This is required for Meteor's live reload to happen on file changes.  And this is something that's completely reversible.

http://blog.mact.me/2014/10/22/yosemite-upgrade-changes-open-file-limit

**Comment by iGitScor** [comment]
Perfect, the modifications work for me, thank you guys !

**Comment by talaviram** [comment]
Worked here also. might be nice for exprience to add this to the installation guide for macOS...
or better suggest some nice Docker based 101 to get dev running.
