### ISSUE TITLE
Reaction init failing due to bcrypt (Mac OS)

### ISSUE THREAD

**Issue by newdesignideas** [reactioncommerce/reaction#1912]
### Expected behavior

Trying to initiate a new reaction project with a simple `reaction init` on Mac OS Sierra with all the requirements installed. 

```
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.7.3 (node-v46 ABI) (falling back to source compile with node-gyp)
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
c++: error: x86_64: No such file or directory
c++: error: unrecognized option '-arch'
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/robertjakobson/Desktop/kruvid-ee/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/robertjakobson/Desktop/kruvid-ee/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt
gyp ERR! node -v v4.7.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/robertjakobson/Desktop/kruvid-ee/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/robertjakobson/Desktop/kruvid-ee/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:854:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
node-pre-gyp ERR! System Darwin 16.4.0
node-pre-gyp ERR! command "/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/robertjakobson/Desktop/kruvid-ee/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt
node-pre-gyp ERR! node -v v4.7.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.32
node-pre-gyp ERR! not ok
Failed to execute '/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node /Users/robertjakobson/Desktop/kruvid-ee/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Users/robertjakobson/Desktop/kruvid-ee/node_modules/bcrypt/lib/binding' (1)
```

### Actual Behavior

The initiation errors out due to bcrypt not being able to be installed

### Steps to Reproduce the Behavior

- Use Mac OS with build tools and command line tools installed and updated to the latest version
- node.js version  7.6.0 with homebrew
- node-gyp version 3.5.0  (updated to the latest version)
- `reaction init` in any random folder

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

Relevant parts from npm-debug.log:

```
108240 verbose stack Error: bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
108240 verbose stack Exit status 1
108240 verbose stack     at EventEmitter.<anonymous> (/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
108240 verbose stack     at emitTwo (events.js:87:13)
108240 verbose stack     at EventEmitter.emit (events.js:172:7)
108240 verbose stack     at ChildProcess.<anonymous> (/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/utils/spawn.js:40:14)
108240 verbose stack     at emitTwo (events.js:87:13)
108240 verbose stack     at ChildProcess.emit (events.js:172:7)
108240 verbose stack     at maybeClose (internal/child_process.js:854:16)
108240 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
108241 verbose pkgid bcrypt@1.0.2
108242 verbose cwd /Users/robertjakobson/Desktop/kruvid-ee
108243 error Darwin 16.4.0
108244 error argv "/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "/Users/robertjakobson/.meteor/packages/meteor-tool/.1.4.3_1.ju6dmy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
108245 error node v4.7.3
108246 error npm  v4.1.2
108247 error code ELIFECYCLE
108248 error bcrypt@1.0.2 install: `node-pre-gyp install --fallback-to-build`
108248 error Exit status 1
108249 error Failed at the bcrypt@1.0.2 install script 'node-pre-gyp install --fallback-to-build'.
108249 error Make sure you have the latest version of node.js and npm installed.
108249 error If you do, this is most likely a problem with the bcrypt package,
108249 error not with npm itself.
108249 error Tell the author that this fails on your system:
108249 error     node-pre-gyp install --fallback-to-build
108249 error You can get information on how to open an issue for this project with:
108249 error     npm bugs bcrypt
108249 error Or if that isn't available, you can get their info via:
108249 error     npm owner ls bcrypt
108249 error There is likely additional logging output above.
108250 verbose exit [ 1, true ]
```

**Comment by aaronjudd** [comment]
We have not yet tested with `1.4.3_1`, we haven't seen this error earlier. You could try installing `npm i -g bcyrpt` to see if a global install works..

**Comment by aaronjudd** [comment]
While you will still see a warning ```node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v46-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for bcrypt@1.0.2 and node@4.8.0 (node-v46 ABI) (falling back to source compile with node-gyp)```

Installation should be working fine, and I'm unable to replicate any blocking issue with Reaction 1.x and Meteor 1.4.3.x

Please re-open remains a blocker.
