### ISSUE TITLE
Error: ENFILE: file table overflow on MacOS Sierra

### ISSUE THREAD

**Issue by gsc-dev** [reactioncommerce/reaction#1938]
For bugs, please fill out the three following sections completely. Failure to provide
this information may result in your ticket being closed without comments.

Are you looking for support for installation/getting started with Reaction? Please go
to our [Gitter](https://gitter.im/reactioncommerce/reaction) channel instead.

### Expected behavior
Reaction starts successfully after fresh instalation

### Actual Behavior
Reaction failing:

```
$ sudo npm install -g reaction-cli
$ reaction init
$ cd reaction
$ reaction
TypeError: Invalid Version: null

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~/code/reaction ]]]]]

=> Started proxy.
=> Meteor 1.4.3.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.
cfs:gridfs: updating npm dependencies -- mongodb, gridfs-stream...
/Users/ronaldo.pontes/.meteor/packages/meteor-tool/.1.4.2_7.1euozxw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: ENFILE: file table overflow, scandir '/Users/ronaldo.pontes/code/reaction/.meteor/local/.build431100.build'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at rmkidsSync (/Users/ronaldo.pontes/.meteor/packages/meteor-tool/.1.4.2_7.1euozxw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/rimraf/rimraf.js:329:11)
    at rmdirSync (/Users/ronaldo.pontes/.meteor/packages/meteor-tool/.1.4.2_7.1euozxw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/rimraf/rimraf.js:322:7)
    at Function.rimrafSync [as sync] (/Users/ronaldo.pontes/.meteor/packages/meteor-tool/.1.4.2_7.1euozxw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/rimraf/rimraf.js:293:9)
    at Object.rm_recursive (/tools/fs/files.js:283:12)
    at Builder.abort (/tools/isobuild/builder.js:696:11)
    at /tools/isobuild/bundler.js:2538:13
    at /tools/isobuild/bundler.js:2827:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2660:31)
    at /tools/isobuild/bundler.js:2607:32
    at Object.withCache (/tools/fs/files.js:1601:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2607:16)
    at /tools/runners/run-app.js:574:36
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:573:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:617:35)
    at AppRunner._fiber (/tools/runners/run-app.js:876:28)
    at /tools/runners/run-app.js:403:12

```

### Steps to Reproduce the Behavior

```
$ sudo npm install -g reaction-cli
$ reaction init
$ cd reaction
$ reaction
```
![image](https://cloud.githubusercontent.com/assets/18435451/23584886/a94b54a2-0166-11e7-9377-37772e647a34.png)

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by gsc-dev** [comment]
Hi,

Running these comments solved the issue, but maybe this should be somewhere in the installation manual?

```
$ echo kern.maxfiles=65536 | sudo tee -a /etc/sysctl.conf
$ echo kern.maxfilesperproc=65536 | sudo tee -a /etc/sysctl.conf
$ sudo sysctl -w kern.maxfiles=65536
$ sudo sysctl -w kern.maxfilesperproc=65536
$ ulimit -n 65536
```
https://github.com/meteor/meteor/issues/8057

**Comment by jshimko** [comment]
Scroll to the bottom...

https://docs.reactioncommerce.com/reaction-docs/master/requirements

**Comment by jshimko** [comment]
It is admittedly easy to miss, but I think we put it there since everyone usually has to start on that page anyway.

**Comment by staringispolite** [comment]
Hi @jshimko! The URL you linked now 404's for me. Do you know where that content moved to?

**Comment by ticean** [comment]
@staringispolite the requirements page was moved to:

https://docs.reactioncommerce.com/docs/requirements

The instructions above are in the [build tools](https://docs.reactioncommerce.com/docs/requirements#build-tools) section.

---

cc @machikoyasuda
