### ISSUE TITLE
Exception is thrown when using Microsoft Azure MongoDB

### ISSUE THREAD

**Issue by weitony111** [reactioncommerce/reaction#1961]
Reproducible steps

1.  setup a Azure MongoDB, which has a connection string like 
````
mongodb://<username>:<password>@<host>:<port>/?ssl=true
````
Note that the Azure MongoDB connection string has a option `ssl=true`.

2. run
````shell
docker run -p 80:3000 -e MONGO_URL=mongodb://<username>:<password>@<host>:<port>/?ssl=true reactioncommerce/reaction:latest
````

3. following exception is thrown and docker exits.
````
=> Starting app on port 3000...
/opt/reaction/dist/bundle/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

Error: key emails.address must not contain '.'
    at Object.Future.wait (/opt/reaction/dist/bundle/programs/server/node_modules/fibers/future.js:449:15)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:828:10)
    at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:677:20)
    at setupUsersCollection (packages/accounts-base/accounts_server.js:1492:9)
    at new AccountsServer (packages/accounts-base/accounts_server.js:51:5)
    at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
    at fileEvaluate (packages/modules-runtime.js:197:9)
    at require (packages/modules-runtime.js:120:16)
    at /opt/reaction/dist/bundle/programs/server/packages/accounts-base.js:2019:15
    at /opt/reaction/dist/bundle/programs/server/packages/accounts-base.js:2030:3
    - - - - -
    at Error (native)
    at serializeInto (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:753:19)
    at serializeObject (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at serializeObject (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:618:17)
    at serializeObject (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:308:18)
    at serializeInto (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/parser/serializer.js:776:17)
    at [object Object].serialize (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/bson/lib/bson/bson.js:58:27)
    at [object Object].Query.toBin (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/commands.js:140:25)
````

By the way, if I use a mlab.com sandbox mongodb instead of Azure MongoDB, there is no such issue. So I suspect that it is because the connection string of Azure MongoDB has some compatibility issue.

Since we are migrating from mlab.com to Microsoft Azure, it's very critical for us. Thanks.

**Comment by jshimko** [comment]
What version of Mongo is it? This doesn't happen with any other Mongo deployment outside of Azure?  If that's the case, then I'm afraid that's an Azure issue and not a Reaction/Meteor issue.  I think you'd unfortunately have to take that up with them.  

Also, the query that causes that error is coming from [code in the base Meteor accounts package](https://github.com/meteor/meteor/blob/580e84d64acb6585233c4f4f0f5aad0c47244f23/packages/accounts-base/accounts_server.js#L51), so it's not Reaction code either way.

Let me know what version of Mongo it is and I'll test it.

Also, for what it's worth, your connection string examples above don't have the database specified.

```sh
# This...
mongodb://<username>:<password>@<host>:<port>/?ssl=true

# Should be this...
mongodb://<username>:<password>@<host>:<port>/<database>?ssl=true
```

I assume that was just a mistake in your example, but thought it was at least worth mentioning since this is an issue nobody else appears to be having.

**Comment by jshimko** [comment]
This is the line that throws...

https://github.com/meteor/meteor/blob/580e84d64acb6585233c4f4f0f5aad0c47244f23/packages/accounts-base/accounts_server.js#L1492

Maybe something with Mongo on Azure that doesn't allow manipulating indexes?

**Comment by weitony111** [comment]
First of all, the MongoDB version of Azure MongoDB is 3.2.0, and I can connect to it using MongoDB shell, so there shouldn't be any problems in Azure side.

Maybe you are correct that Mongo on Azure doesn't allow manipulating indexes, but to be honest, I don't quite understand why the exception has anything to do with the connection string, since the exception occurs when it is operating the users in collections. So I also test it by specifying `REACTION_EMAIL`, `REACTION_USER` and `REACTION_AUTH`; however the issue is still happening.

Although the issue has nothing to do with Reaction, I'm really appreciating your effort in investigating it. Thank you.

Regarding the concern about my connection string, kindly take a look at the following which is copied from [MongoDB reference](https://docs.mongodb.com/v3.2/reference/connection-string/).

> /database	Optional. The name of the database to authenticate if the connection string includes authentication credentials in the form of **username:password<nolink>@**. If **/database** is not specified and the connection string includes credentials, the driver will authenticate to the **admin** database.

Since I was accessing **admin** database, I didn't specify **\<database\>**; however, even though I created another database and specified **\<database\>**, same issue is still happening.

**Comment by jshimko** [comment]
Yeah, I wasn't saying I thought it had anything to do with the connection string.  I was just pointing it out.  Even if it will allow you to do that, I don't think it's a safe bet to assume you can leave the database name off.  Sure, it may not be necessary, but there's some value in knowing for sure which database you're actually accessing.  

Also, the admin database is the default db that Mongo users and permissions are stored in.  I wouldn't make the assumption that it's ok to use that for your apps.  You should always be creating a new database for every connected app.

That said, maybe that's exactly what your issue is.  The admin database may have restrictions on it.  Try creating a new/empty database and connecting Reaction to that instead.

**Comment by weitony111** [comment]
Yeah, as I mentioned in my previous comment, I did try to create a new database and connect reaction to it; however, the issue is still happening. I will test `db.collection.ensureIndex` in MongoDB cli later.

**Comment by jshimko** [comment]
What is the state of this issue @weitony111?

**Comment by weitony111** [comment]
It turns out that this issue is solely due to Azure MongoDB. It looks like their service currently is not mature yet, which results in many incompatibility issue (not only `db.collection.ensureIndex`, but also other index related operations). I think this bug can be closed now since reaction has nothing to do with it.

**Comment by weitony111** [comment]
There is a similar issue.

https://github.com/XervoIO/demeteorizer/issues/265

Basically the root cause is exactly the same. I have also tried to contact Microsoft Azure team. Though they are aware of this issue and promised to fix, until now it is not fixed yet, since someone recently reported this issue in the above link.

**Comment by jshimko** [comment]
Thank you for the update @weitony111

**Comment by garychapman** [comment]
October 17, 2017 - this issue still seems to be occurring FWIW.

**Comment by ramzauchenna** [comment]
Still have same issue with Azure too
