### ISSUE TITLE
Cannot read property 'language' of undefined

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#1975]
When running `reaction test`, server console logs an uncaught exception
```
I20170313-16:45:47.270(-7)? ․․․․․․․․Exception from sub Translations id BFhbkikFzj6TNQpkG TypeError: Cannot read property 'language' of undefined
I20170313-16:45:47.271(-7)?     at [object Object].<anonymous> (server/publications/collections/translations.js:13:24)
I20170313-16:45:47.271(-7)?     at packages/matb33_collection-hooks.js:307:21
I20170313-16:45:47.272(-7)?     at [object Object]._.extend.withValue (packages/meteor.js:1122:17)```

**Comment by zenweasel** [comment]
@aaronjudd I'm not seeing this in `development` on my local version or a fresh clone. Can you double-check if this is still happening for you?

I did remember seeing this at some point.

**Comment by aaronjudd** [comment]
I'm not able to replicate this anymore with 1.1.x development branch.

**Comment by zenweasel** [comment]
Closing. Can't reproduce.
