### ISSUE TITLE
app is crashing

### ISSUE THREAD

**Issue by solancer** [reactioncommerce/reaction#2017]
Your app is crashing. Here's the latest log:
Started MongoDB.
Errors prevented startup:

While processing files with ecmascript (for target web.browser):
/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/plugin.js:131:13: Plugin 0 specified in "foreign" provided an invalid property of "__wrapped__"
  at Plugin.init (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/plugin.js:131:13)
  at Function.normalisePlugin (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
  at /Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
  at Array.map (native)
  at Function.normalisePlugins (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
  at OptionManager.mergeOptions (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:233:36)
  at /Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14
  at /Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:322:22
  at Array.map (native)
  at OptionManager.resolvePresets (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:274:20)
  at OptionManager.mergePresets (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:263:10)
  at OptionManager.mergeOptions (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:14)
  at OptionManager.init (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
  at File.initOptions (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/index.js:216:65)
  at new File (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/index.js:139:24)
  at Pipeline.transformFromAst (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/pipeline.js:69:16)
  at compile (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:65:43)
  at Cache.Cp.get (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:94:19)
  at Object.compile (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:48:23)
  at Object.Babel.compile (packages/babel-compiler.js:48:24)
  at packages/babel-compiler.js:162:22
  at Function.time (/tools/tool-env/profile.js:305:10)
  at profile (packages/babel-compiler.js:192:20)
  at BabelCompiler.BCp.processOneFileForTarget (packages/babel-compiler.js:161:20)
  at BabelCompiler.<anonymous> (packages/babel-compiler.js:93:26)
  at Array.forEach (native)
  at BabelCompiler.BCp.processFilesForTarget (packages/babel-compiler.js:92:14)

While processing files with less (for target web.browser):
imports/plugins/included/default-theme/client/styles/main.less:51: Unknown import: {}/node_modules/react-select/less/default.less

While minifying app stylesheet:
error: Can't load npm module 'autoprefixer' from packages/minifier-postcss_plugin.js. Check your Npm.depends().

Your application has errors. Waiting for file change.
----

linuxsavvy-mbp:reaction srinivas$ reaction

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Setting up style imports...

[[[[[ ~/Desktop/sloop/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.

Unable to resolve some modules:

  "nodemailer" in /Users/srinivas/Desktop/sloop/reaction/server/jobs/email.js
(os.osx.x86_64)
  "handlebars" in
/Users/srinivas/Desktop/sloop/reaction/server/api/core/templates.js
(os.osx.x86_64)
  "postcss" in /Users/srinivas/Desktop/sloop/reaction/server/api/core/ui.js
(os.osx.x86_64)
  "postcss-js" in /Users/srinivas/Desktop/sloop/reaction/server/api/core/ui.js
(os.osx.x86_64)
  "autoprefixer" in
/Users/srinivas/Desktop/sloop/reaction/server/api/core/ui.js (os.osx.x86_64)
  "css-annotation" in
/Users/srinivas/Desktop/sloop/reaction/server/api/core/ui.js (os.osx.x86_64)
  "fibers/future" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/payments-braintree/server/methods/braintreeApi.js
(os.osx.x86_64)
  "node-geocoder" in
/Users/srinivas/Desktop/sloop/reaction/server/api/geocoder.js (os.osx.x86_64)
  "bunyan-format" in
/Users/srinivas/Desktop/sloop/reaction/server/api/logger.js (os.osx.x86_64)
  "bunyan-loggly" in
/Users/srinivas/Desktop/sloop/reaction/server/api/logger.js (os.osx.x86_64)
  "prerender-node" in
/Users/srinivas/Desktop/sloop/reaction/server/startup/prerender.js
(os.osx.x86_64)
  "deep-diff" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/core/revisions/server/hooks.js
(os.osx.x86_64)
  "later" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/jobcontrol/server/jobs/cleanup.js
(os.osx.x86_64)
  "@reactioncommerce/authorize-net" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/payments-authnet/server/methods/authnet.js
(os.osx.x86_64)
  "braintree" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/payments-braintree/server/methods/braintreeApi.js
(os.osx.x86_64)
  "paypal-rest-sdk" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/payments-paypal/server/methods/payflowproApi.js
(os.osx.x86_64)
  "stripe" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/payments-stripe/server/methods/stripeapi.js
(os.osx.x86_64)
  "shippo" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/shippo/server/methods/shippoapi.js
(os.osx.x86_64)
  "flatten-obj" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/shippo/server/methods/carriers.js
(os.osx.x86_64)
  "twilio" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/sms/server/methods/sms.js
(os.osx.x86_64)
  "nexmo" in
/Users/srinivas/Desktop/sloop/reaction/imports/plugins/included/sms/server/methods/sms.js
(os.osx.x86_64)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save nodemailer handlebars postcss postcss-js
autoprefixer css-annotation fibers node-geocoder bunyan-format bunyan-loggly
prerender-node deep-diff later @reactioncommerce braintree paypal-rest-sdk
stripe shippo flatten-obj twilio nexmo

=> Errors prevented startup:

   While processing files with ecmascript (for target web.browser):

   /Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/plugin.js:131:13:
   Plugin 0 specified in "foreign" provided an invalid property of
   "__wrapped__"
   at Plugin.init
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/plugin.js:131:13)
   at Function.normalisePlugin
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
   at
   /Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
   at Array.map (native)
   at Function.normalisePlugins
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
   at OptionManager.mergeOptions
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:233:36)
   at
   /Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14
   at
   /Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:322:22
   at Array.map (native)
   at OptionManager.resolvePresets
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:274:20)
   at OptionManager.mergePresets
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:263:10)
   at OptionManager.mergeOptions
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:14)
   at OptionManager.init
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
   at File.initOptions
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/index.js:216:65)
   at new File
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/file/index.js:139:24)
   at Pipeline.transformFromAst
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/babel-core/lib/transformation/pipeline.js:69:16)
   at compile
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:65:43)
   at Cache.Cp.get
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/cache.js:94:19)
   at Object.compile
   (/Users/srinivas/.meteor/packages/ecmascript/.0.6.3.v8afs8++os+web.browser+web.cordova/plugin.compile-ecmascript.os/npm/node_modules/meteor/babel-compiler/node_modules/meteor-babel/index.js:48:23)
   at Object.Babel.compile (packages/babel-compiler.js:48:24)
   at packages/babel-compiler.js:162:22
   at Function.time (/tools/tool-env/profile.js:305:10)
   at profile (packages/babel-compiler.js:192:20)
   at BabelCompiler.BCp.processOneFileForTarget
   (packages/babel-compiler.js:161:20)
   at BabelCompiler.<anonymous> (packages/babel-compiler.js:93:26)
   at Array.forEach (native)
   at BabelCompiler.BCp.processFilesForTarget
   (packages/babel-compiler.js:92:14)

   While processing files with less (for target web.browser):
   imports/plugins/included/default-theme/client/styles/main.less:51: Unknown
   import: {}/node_modules/react-select/less/default.less

   While minifying app stylesheet:
   error: Can't load npm module 'autoprefixer' from
   packages/minifier-postcss_plugin.js. Check your Npm.depends().

=> Your application has errors. Waiting for file change.

### Steps to Reproduce the Behavior

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by zenweasel** [comment]
@solancer Hey, this is not a problem with the application itself but something with your installation. If you need installation support please do so through our [Gitter channel](https://gitter.im/reactioncommerce/reaction) and we would be glad to help.

**Comment by dtaipov** [comment]
@solancer `npm install` solved the problem for me.
Not sure if this is a proper way to solve this problem though.

**Comment by kkdg** [comment]
This is mostly due to creating a project by downloading source files manually. I had same problem when git clone from github repo, but fixed it using reaction-cli with command 'reaction init'
