### ISSUE TITLE
Shippo API Version 2017-03-29 breaking changes

### ISSUE THREAD

**Issue by vigyano** [reactioncommerce/reaction#2069]
### Expected behavior
Shippo API key should allow reaction to pull carrier rates at checkout

### Actual Behavior
On checkout after address, no shipping information and throws error 
error: 
```
Exception while invoking method 'accounts/addressBookAdd' TypeError: Cannot read property 'map' of undefined
    at ratesParser (imports/plugins/included/shippo/server/methods/shippo.js:48:10)
    at [object Object].methods.shippo/getShippingRatesForCart (imports/plugins/included/shippo/server/methods/shippo.js:414:29)
    at packages\check.js:130:16
    at [object Object]._.extend.withValue (packages\meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages\check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:1650:18
    at [object Object]._.extend.withValue (packages\meteor.js:1122:17)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1649:45)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1592:17)
    at packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:67:23
    at [object Object]._.extend.withValue (packages\meteor.js:1122:17)
    at Object.Meteor.(anonymous function) [as call] (packages/kadira:flow-router-ssr/server/plugins/ssr_data.js:66:44)
    at getShippingRates (imports/plugins/included/shippo/server/hooks/rates.js:55:34)
    at server/api/hooks.js:53:14
    at Array.reduce (native)
    at Object.Hooks.Events.run (server/api/hooks.js:52:22)
    at [object Object].methods.shipping/getShippingRates (server/methods/core/shipping.js:81:18)
    at packages\check.js:130:16
    at [object Object]._.extend.withValue (packages\meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages\check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)

```

New API Version 2017-03-29 
breaks the `rates_list` since the name has been changed to `rates`, so that the time

### Steps to Reproduce the Behavior

1. Create New user on or after March 31st 2017 after Version 2017-03-29 release
2. Get the API key from shippo dashboard
3. Configure Shippo API key in reaction 
4. Add product to cart and checkout
5. Add address at checkout and click "Save and continue"

**Comment by vigyano** [comment]
@zenweasel posted in gitter channel the issue is at https://github.com/reactioncommerce/reaction/blob/b326c23e9e459f52278424f67d71b502853e34bc/imports/plugins/included/shippo/server/methods/shippo.js#L411-L411

where `rates_list` changed to `rates` in API Version 2017-03-29
https://goshippo.com/docs/changelog

**Comment by impactmass** [comment]
some things:
- [ ] `parcel` in payload should now be `parcels` (array)
- [ ] `rates_list` in response is now `rates`
- [ ] backward compatibility

**Comment by impactmass** [comment]
An immediate/interim solution is to explicitly set the Shippo API version being used in Reaction (i.e `shippoObj.set("version", "YYYY-MM-DD")`)..... that way all requests are made at that API level.

[This](https://github.com/reactioncommerce/reaction/commit/137a12897ed4a70d4c58948bea5699fd4438a272) can suffice till we update the Shippo plugin in Reaction to work with the latest shippo API release.
cc @zenweasel

**Comment by impactmass** [comment]
@zenweasel we can close this as well, since it's a version thing to be handled in #2137
