### ISSUE TITLE
can't build reaction

### ISSUE THREAD

**Issue by hollligan** [reactioncommerce/reaction#2072]
Hello, I can not build docker image (docker build-t reaction_modified .).

Steps to Reproduce the Behavior:

>git clone https://github.com/reactioncommerce/reaction.git
Cloning into 'reaction'...
remote: Counting objects: 64834, done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 64834 (delta 124), reused 1 (delta 1), pack-reused 64507
Receiving objects: 100% (64834/64834), 33.35 MiB | 3.54 MiB/s, done.
Resolving deltas: 100% (34850/34850), done.
Checking out files: 100% (2155/2155), done.

>docker build -t reaction_modified .
..
Error: EXDEV: cross-device link not permitted, rename '/opt/reaction/dist/bundle' -> '/opt/reaction/dist/bundle-garbage-uxp1ip'
    at Error (native)
    at Object.fs.renameSync (fs.js:681:18)
    at Object.wrapper [as rename] (/tools/fs/files.js:1535:35)
    at Object.files.renameDirAlmostAtomically (/tools/fs/files.js:965:11)
    at Builder.complete (/tools/isobuild/builder.js:690:13)
    at /tools/isobuild/bundler.js:2529:13
    at /tools/isobuild/bundler.js:2837:22
    at /tools/utils/buildmessage.js:271:13
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object]._.extend.withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at bundle (/tools/isobuild/bundler.js:2670:31)
    at /tools/isobuild/bundler.js:2617:32
    at Object.withCache (/tools/fs/files.js:1601:12)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2617:16)
    at buildCommand (/tools/cli/commands.js:949:30)
    at Command.func (/tools/cli/commands.js:824:12)
    at /tools/cli/main.js:1483:23
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1

>docker image ls --filter "reference=reaction_*"
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

[reaction build full log.txt](https://github.com/reactioncommerce/reaction/files/889388/reaction.build.log.txt)

**Comment by aaronjudd** [comment]
This is a duplicate issue, see #1946
