### ISSUE TITLE
Revision control architecture adjustments

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#2081]
Related to #2079 

Re-adjust the architecture of the revision control system to avoid the following error.

```
Exception in queued task: Error: Could not find element with id NCHtKw9CaT5WssF4s to change
    at [object Object]._.extend.changed (packages/ddp-server/livedata_server.js:188:13)
    at [object Object]._.extend.changed (packages/ddp-server/livedata_server.js:403:10)
    at [object Object]._.extend.changed (packages/ddp-server/livedata_server.js:1262:19)
    at Object.Revisions.find.observe.changed (server/publications/collections/products.js:346:20)
    at [object Object].observeChangesCallbacks.changed (packages/minimongo/observe.js:162:28)
    at self.applyChange.changed (packages/minimongo/observe.js:66:44)
    at packages/mongo/observe_multiplex.js:182:30
    at Array.forEach (native)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at Object.task (packages/mongo/observe_multiplex.js:176:9)
    at [object Object]._.extend._run (packages/meteor.js:807:18)
    at packages/meteor.js:785:14
```

As far as I can tell, this happens because of the collection observables in the `Products`, `Product`, and `Media` publications. A possible solution is to remove collection observables and find a better solution, whatever that may be.

This is dependent on removing the old Product Detail Page in https://github.com/reactioncommerce/reaction/issues/2080, so we don't have to worry about backwards compatibility.

**Comment by aldeed** [comment]
Fixed in 1.9.0
