### ISSUE TITLE
Error sending or verifying email

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2116]
When starting Reaction Commerce with a `MAIL_URL` environment variable set, emails fail to send with the following error:
```
16:14:07.331Z  INFO Reaction: Load default data from /private/data/
16:14:07.656Z  INFO Reaction: JobServer started
16:14:07.690Z  INFO Reaction: Loaded "/private/settings/reaction.json" for registry fixture import
16:14:11.946Z  INFO Reaction: Reaction Version: 1.1.0
16:14:12.016Z  WARN Reaction: OpenExchangeRates API not configured. Not adding fetchRates job
16:14:12.022Z  WARN Reaction: OpenExchangeRates API not configured. Not adding flushRates job
16:14:12.267Z  INFO Reaction: Reaction initialization finished.
=> Meteor server restarted
16:14:17.930Z ERROR Reaction:
  140736349344704:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
```

Attempting to enter email credentials via the admin console produces the following error after clicking 'Save'
```
  --
  Error: 140736349344704:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
      at Object.Future.wait (/Users/sn/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
      at packages/meteor.js:213:24
      at [object Object].Meteor.methods.email/verifySettings (server/methods/email.js:44:14)
      at packages/check.js:130:16
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
      at packages/ddp-server/livedata_server.js:719:19
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at packages/ddp-server/livedata_server.js:717:40
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at packages/ddp-server/livedata_server.js:715:46
      at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
      at packages/ddp-server/livedata_server.js:559:43
      - - - - -

      at Error (native)
16:14:17.935Z ERROR Reaction:
  140736349344704:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

  --
  Error: 140736349344704:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:
      at Object.Future.wait (/Users/sn/.meteor/packages/meteor-tool/.1.4.3_2.1bvf0xf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
      at packages/meteor.js:213:24
      at [object Object].Meteor.methods.email/verifySettings (server/methods/email.js:44:14)
      at packages/check.js:130:16
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
      at packages/ddp-server/livedata_server.js:719:19
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at packages/ddp-server/livedata_server.js:717:40
      at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
      at packages/ddp-server/livedata_server.js:715:46
      at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
      at packages/ddp-server/livedata_server.js:559:43
      - - - - -

      at Error (native)
```

I'm certain this is an issue with our implementation and not with the providers I tried (Postmark and Mailgun) and not with my connection string.

**Comment by jshimko** [comment]
This is almost always a combination of the `port` and `secure` options not being correct in the Nodemailer config.

https://nodemailer.com/smtp/

At one point, there was an issue with the port needing to be a Number instead of a String, but I [fixed that a while back](https://github.com/reactioncommerce/reaction/blob/master/server/api/core/email/config.js#L82).

Also, note that manually setting `MAIL_URL` overrides any values that you can set in the dashboard, so if you leave the environment variable set, nothing you do in the dashboard will have any effect.  

That said, make sure you start the app _without_ `MAIL_URL` set and then try the presets in the dashboard settings.  Those are the official configs that are published in the [`nodemailer-wellknown`](https://github.com/nodemailer/nodemailer-wellknown) package.

**Comment by jshimko** [comment]
And yeah, the fact that setting `MAIL_URL` manually makes the dashboard settings useless is a problem all by itself.  We ideally need to make it clear in the dashboard that the settings have been overridden via environment variables.  That gets complicated quickly though because the dashboard settings also _set_ the `MAIL_URL` if it's not set already (because some Meteor packages rely on Meteor's email package and that relies on `MAIL_URL`).  That said, we'd need to detect whether `MAIL_URL` was set manually or via the dashboard settings and then show that status in the dashboard.

**Comment by jshimko** [comment]
Related #1442

**Comment by zenweasel** [comment]
@spencern / @jshimko Is this issue fixed?
