### ISSUE TITLE
Cannot read property 'domains' of undefined

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2336]
Resolve `Cannot read property 'domains' of undefined`.

To reproduce, replicate, run `reaction test`.

```
I20170523-21:42:00.576(0)?   TypeError: Cannot read property 'domains' of undefined
I20170523-21:42:00.590(0)?       at Object._setDomain [as setDomain] (server/api/core/setDomain.js:30:3)
I20170523-21:42:00.590(0)?       at Object.added (server/startup/registry.js:14:5)
I20170523-21:42:00.590(0)?       at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:28)
I20170523-21:42:00.593(0)?       at self.applyChange.added (packages/minimongo/observe.js:53:44)
I20170523-21:42:00.594(0)?       at packages/mongo/observe_multiplex.js:182:30
I20170523-21:42:00.594(0)?       at Array.forEach (native)
I20170523-21:42:00.596(0)?       at Function._.each._.forEach (packages/underscore.js:139:11)
I20170523-21:42:00.596(0)?       at Object.task (packages/mongo/observe_multiplex.js:176:9)
I20170523-21:42:00.598(0)?       at [object Object]._.extend._run (packages/meteor.js:807:18)
I20170523-21:42:00.598(0)?       at packages/meteor.js:785:14
```

```
Node: 7.5.0
NPM: 4.1.2
Meteor Node: 4.8.2
Meteor NPM: 4.5.0
Reaction CLI: 0.8.4
Reaction: 1.2.0
Reaction branch: joykare-testing-2066
Docker: 17.03.1-ce
```

**Comment by aaronjudd** [comment]
Possibly related to #2329?

**Comment by janus-reith** [comment]
I also get that error on marketplace branch, but not just for test but upon startup, after adding my previous customizations to the new code - Couldn't find the file yet that triggers the error.

**Comment by aaronjudd** [comment]
@zenweasel please verify this is resolved.

**Comment by zenweasel** [comment]
Closing. Can no longer replicate.
