### ISSUE TITLE
dynamicImportInfo is not defined

### ISSUE THREAD

**Issue by virtualLast** [reactioncommerce/reaction#2391]
### Expected behavior

app starts and runs on localhost

### Actual Behavior

application crashing, waiting for file change

### Steps to Reproduce the Behavior

I updated my meteor - ran through the install instructions in the reaction docs (for osx), then had to run `meteor --allow-incompatible-update` to fix a different issue, now I am getting the following error output

---CODE DUMP
```
W20170602-16:24:39.265(1)? (STDERR) /Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170602-16:24:39.780(1)? (STDERR) 						throw(ex);
W20170602-16:24:39.783(1)? (STDERR) 						^
W20170602-16:24:39.783(1)? (STDERR)
W20170602-16:24:39.784(1)? (STDERR) ReferenceError: dynamicImportInfo is not defined
W20170602-16:24:39.785(1)? (STDERR)     at meteorInstall.node_modules.meteor.dynamic-import.server.js (packages/dynamic-import/server.js:15:13)
W20170602-16:24:39.787(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-16:24:39.788(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-16:24:39.788(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:495:15
W20170602-16:24:39.789(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:501:3
W20170602-16:24:39.790(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:303:34
W20170602-16:24:39.791(1)? (STDERR)     at Array.forEach (native)
W20170602-16:24:39.794(1)? (STDERR)     at Function._.each._.forEach (/Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170602-16:24:39.794(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:128:5
W20170602-16:24:39.794(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:352:5
W20170602-16:24:39.795(1)? (STDERR)     at Function.run (/Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/profile.js:510:12)
W20170602-16:24:39.795(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
W20170602-16:26:05.625(1)? (STDERR) /Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170602-16:26:05.627(1)? (STDERR) 						throw(ex);
W20170602-16:26:05.628(1)? (STDERR) 						^
W20170602-16:26:05.629(1)? (STDERR)
W20170602-16:26:05.629(1)? (STDERR) ReferenceError: dynamicImportInfo is not defined
W20170602-16:26:05.630(1)? (STDERR)     at meteorInstall.node_modules.meteor.dynamic-import.server.js (packages/dynamic-import/server.js:15:13)
W20170602-16:26:05.631(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-16:26:05.633(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-16:26:05.637(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:495:15
W20170602-16:26:05.640(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:501:3
W20170602-16:26:05.642(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:303:34
W20170602-16:26:05.643(1)? (STDERR)     at Array.forEach (native)
W20170602-16:26:05.643(1)? (STDERR)     at Function._.each._.forEach (/Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170602-16:26:05.645(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:128:5
W20170602-16:26:05.645(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:352:5
W20170602-16:26:05.647(1)? (STDERR)     at Function.run (/Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/profile.js:510:12)
W20170602-16:26:05.648(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
W20170602-16:26:36.874(1)? (STDERR) /Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170602-16:26:36.875(1)? (STDERR) 						throw(ex);
W20170602-16:26:36.876(1)? (STDERR) 						^
W20170602-16:26:36.877(1)? (STDERR)
W20170602-16:26:36.877(1)? (STDERR) ReferenceError: dynamicImportInfo is not defined
W20170602-16:26:36.877(1)? (STDERR)     at meteorInstall.node_modules.meteor.dynamic-import.server.js (packages/dynamic-import/server.js:15:13)
W20170602-16:26:36.878(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-16:26:36.878(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-16:26:36.879(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:495:15
W20170602-16:26:36.879(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:501:3
W20170602-16:26:36.880(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:303:34
W20170602-16:26:36.880(1)? (STDERR)     at Array.forEach (native)
W20170602-16:26:36.881(1)? (STDERR)     at Function._.each._.forEach (/Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170602-16:26:36.881(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:128:5
W20170602-16:26:36.882(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:352:5
W20170602-16:26:36.882(1)? (STDERR)     at Function.run (/Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/profile.js:510:12)
W20170602-16:26:36.883(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
W20170602-16:26:56.626(1)? (STDERR) /Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170602-16:26:56.627(1)? (STDERR) 						throw(ex);
W20170602-16:26:56.628(1)? (STDERR) 						^
W20170602-16:26:56.628(1)? (STDERR)
W20170602-16:26:56.629(1)? (STDERR) ReferenceError: dynamicImportInfo is not defined
W20170602-16:26:56.629(1)? (STDERR)     at meteorInstall.node_modules.meteor.dynamic-import.server.js (packages/dynamic-import/server.js:15:13)
W20170602-16:26:56.630(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-16:26:56.631(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-16:26:56.632(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:495:15
W20170602-16:26:56.633(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:501:3
W20170602-16:26:56.635(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:303:34
W20170602-16:26:56.636(1)? (STDERR)     at Array.forEach (native)
W20170602-16:26:56.640(1)? (STDERR)     at Function._.each._.forEach (/Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170602-16:26:56.640(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:128:5
W20170602-16:26:56.641(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:352:5
W20170602-16:26:56.642(1)? (STDERR)     at Function.run (/Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/profile.js:510:12)
W20170602-16:26:56.644(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
W20170602-16:27:15.393(1)? (STDERR) /Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170602-16:27:15.394(1)? (STDERR) 						throw(ex);
W20170602-16:27:15.394(1)? (STDERR) 						^
W20170602-16:27:15.395(1)? (STDERR)
W20170602-16:27:15.395(1)? (STDERR) ReferenceError: dynamicImportInfo is not defined
W20170602-16:27:15.396(1)? (STDERR)     at meteorInstall.node_modules.meteor.dynamic-import.server.js (packages/dynamic-import/server.js:15:13)
W20170602-16:27:15.396(1)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170602-16:27:15.397(1)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170602-16:27:15.397(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:495:15
W20170602-16:27:15.398(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/packages/dynamic-import.js:501:3
W20170602-16:27:15.399(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:303:34
W20170602-16:27:15.399(1)? (STDERR)     at Array.forEach (native)
W20170602-16:27:15.400(1)? (STDERR)     at Function._.each._.forEach (/Users/mikelast/.meteor/packages/meteor-tool/.1.4.4_3.1cqsr0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170602-16:27:15.401(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:128:5
W20170602-16:27:15.401(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:352:5
W20170602-16:27:15.402(1)? (STDERR)     at Function.run (/Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/profile.js:510:12)
W20170602-16:27:15.403(1)? (STDERR)     at /Users/mikelast/Sites/reaction/.meteor/local/build/programs/server/boot.js:351:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```
---END CODE DUMP

### Versions
(run `reaction -v` from your reaction directory)
Node: 7.8.0
NPM: 4.2.0
Meteor Node: 4.8.3
Meteor NPM: 4.5.0
Reaction CLI: 0.9.2
Reaction: 1.2.0
Reaction branch: master

For enhancements or other issues, please describe in as much detail as
possible how the app should be changed and how this would benefit
users/developers

**Comment by aaronjudd** [comment]
dynamic import is a meteor 1.5 package, I'm guessing that when you updated to allow incompatible packages, one of the incompatible packages is requiring meteor 1.5 already for dynamic imports...  we have a branch and PR #2371 open for Meteor 1.5 updates, you might want to try that.

**Comment by aaronjudd** [comment]
Close, please re-open if this wasn't the solution.
