### ISSUE TITLE
Uncaught error in setDomain during tests

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2454]
Running `reaction test`, I see an error related to #2453 and #2329 

```I20170616-18:25:48.915(-7)? ․․․․․01:25:48.915Z ERROR Reaction: Failed to determine default shop.
I20170616-18:25:48.917(-7)?   TypeError: Cannot read property 'domains' of undefined
I20170616-18:25:48.917(-7)?       at Object._setDomain [as setDomain] (server/api/core/setDomain.js:30:3)
I20170616-18:25:48.917(-7)?       at Object.added (server/startup/registry.js:14:5)
I20170616-18:25:48.920(-7)?       at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:28)
I20170616-18:25:48.921(-7)?       at self.applyChange.added (packages/minimongo/observe.js:53:44)
I20170616-18:25:48.922(-7)?       at packages/mongo/observe_multiplex.js:182:30
I20170616-18:25:48.923(-7)?       at Array.forEach (native)
I20170616-18:25:48.925(-7)?       at Function._.each._.forEach (packages/underscore.js:139:11)
I20170616-18:25:48.925(-7)?       at Object.task (packages/mongo/observe_multiplex.js:176:9)
I20170616-18:25:48.927(-7)?       at [object Object]._.extend._run (packages/meteor.js:807:18)
I20170616-18:25:48.928(-7)?       at packages/meteor.js:785:14
```

```
Node: 7.5.0
NPM: 5.0.0
Meteor Node: 4.8.3
Meteor NPM: 4.6.1
Reaction CLI: 0.9.3
Reaction: 1.3.0
Reaction branch: Release-1.3.0
Docker: 17.03.1-ce
```

**Comment by aaronjudd** [comment]
Duplicate of #2336
