### ISSUE TITLE
[Marketplace] Receive error when trying to archive product

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2620]
### Expected behavior
Should be able to archive a product w/o an error

### Actual Behavior
Receive an error on the server-side:
```
Exception while invoking method 'products/archiveProduct' Error: Mongo selector can't be an array.
    at Function.Mongo.Collection._rewriteSelector (packages/mongo/collection.js:377:11)
    at new CursorDescription (packages/mongo/mongo_driver.js:881:36)
    at [object Object].MongoConnection.find (packages/mongo/mongo_driver.js:807:11)
    at [object Object].MongoConnection.findOne (packages/mongo/mongo_driver.js:818:15)
    at Object.<anonymous> (packages/matb33_collection-hooks.js:819:16)
    at Object.collection.(anonymous function) [as findOne] (packages/matb33_collection-hooks.js:146:21)
    at [object Object]._.extend.findOne (packages/mongo/collection.js:334:29)
    at [object Object].productsArchiveProduct (server/methods/catalog.js:765:30)
    at packages/check.js:129:16
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at packages/ddp-server/livedata_server.js:717:46
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
```

### Steps to Reproduce the Behavior
I verified that this doesn't happen on `development`

1. Login as admin
1. Click on default product
1. Select "Clone product"
1. Select newly created product
1. Click on archive
1. Observe error on client and server

### Versions
```
Node: 7.10.0
NPM: 5.0.3
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: marketplace
Docker: 17.06.0-ce
Commit: b6e18a4b5a35b852bd75648ae395a2f4b77eae81
```

**Comment by zenweasel** [comment]
Closed via #2650
