### ISSUE TITLE
Receive error on server when a new user logs on for the first time

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#2821]
### Expected behavior
No errors

### Actual Behavior
Receive the following error in the server console:
```
Exception in onLogin callback: Error: Match error: Failed Match.OneOf, Match.Maybe or Match.Optional validation
    at exports.check (packages/check.js:56:15)
    at [object Object].cartMergeCart (server/methods/core/cart.js:114:5)
    at packages/check.js:129:16
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:128:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:1686:15
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at packages/ddp-server/livedata_server.js:1684:36
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1622:26)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1604:17)
    at server/startup/accounts.js:237:21
    at runAndHandleExceptions (packages/callback-hook.js:152:24)
    at packages/callback-hook.js:159:12
    at packages/accounts-base/accounts_server.js:164:5
```

### Steps to Reproduce the Behavior
1. Login as admin
1. Invite a user to a shop
1. Open the invite email and copy the URL
1. Open that URL in an incognito browser
1. Observe error

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.11.0
Reaction: 1.5.0
Reaction branch: brent-fix-issue-2765
Docker: 17.06.2-ce
```

**Comment by zenweasel** [comment]
Closed via #2857
