### ISSUE TITLE
userId is not published by new Reactive Aggregate orders publication

### ISSUE THREAD

**Issue by spencern** [reactioncommerce/reaction#2955]
While reviewing #2770, @kieha and I came across an issue in the Reactive Aggregate Orders publication where sometimes the `userId` of an order is not published. That causes an error when sending in-app notifications of the order being shipped.

Clicking this button generated an error on the server, which bubbled up to the client.

![image](https://user-images.githubusercontent.com/1203639/30884696-d241ca5e-a2cd-11e7-811b-cf2ea30890df.png)

Client Error:
```
Error invoking Method 'notification/send': Match failed [400]
```

Server Error:
```
Exception while invoking method 'notification/send' Error: Match error: Expected string, got null
    at exports.check (packages/check.js:55:15)
    at [object Object].notificationSend (imports/plugins/included/notifications/server/methods/notifications.js:21:5)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:717:46
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]
```

A fix is on the way.

**Comment by spencern** [comment]
Fixed by #2956
