### ISSUE TITLE
Error handling in checkout add address validation

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#2981]
Error in Platform deployed `1.4.3` where shipping is not being configured from `reaction.json` on startup:

Prevents users from adding address.
Browser console:
```
Error: Failed to add address: 
    at 5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:281
    at y._callback (5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:1)
    at y._maybeInvokeCallback (5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:65)
    at y.dataVisible (5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:65)
    at 5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:65
    at Array.forEach (<anonymous>)
    at Function.A.each.A.forEach (5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:25)
    at b._runAfterUpdateCallbacks (5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:65)
    at b._performWrites (5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:65)
    at b._flushBufferedWrites (5c00f9aa4695e7c969388c2bd2008100d7ff2339.js:65)
```

![sharing_frame_window](https://user-images.githubusercontent.com/439959/31023836-fcfba8a2-a4f1-11e7-8a88-f1a3e7139a23.png)

Server console:

```
15:26:19.553Z  INFO Reaction: Load default data from /private/data/
15:26:20.889Z  INFO Reaction: JobServer started
15:26:20.893Z  INFO Reaction: Loaded REACTION_REGISTRY environment variable for registry fixture import
15:26:28.154Z  INFO Reaction: Using environment variables to create admin user
15:26:32.909Z  WARN Reaction:

   *********************************

    IMPORTANT! DEFAULT ADMIN INFO

    EMAIL/LOGIN: testing@reactioncommerce

    PASSWORD: XXXXXXXXXXXXXXX

   *********************************


15:26:32.915Z  INFO Reaction: Reaction Version: 1.4.4
15:26:33.189Z  INFO Reaction: Migrating from version 0 -> 4
15:26:33.190Z  INFO Reaction: Running up() on version 1
15:26:33.235Z  INFO Reaction: Running up() on version 2
15:26:33.256Z  INFO Reaction: Running up() on version 3
15:26:33.300Z  INFO Reaction: Loaded REACTION_REGISTRY environment variable for registry fixture import
15:26:37.417Z  INFO Reaction: Running up() on version 4
15:26:37.441Z  INFO Reaction: Finished migrating.
15:26:38.151Z  INFO Reaction: Reaction initialization finished.
15:35:50.282Z ERROR Reaction: The data you sent was not accepted as valid
15:36:09.054Z ERROR Reaction: The data you sent was not accepted as valid
15:36:40.593Z ERROR Reaction: The data you sent was not accepted as valid
15:37:08.638Z ERROR Reaction: The data you sent was not accepted as valid
15:37:26.243Z ERROR Reaction: The data you sent was not accepted as valid
Exception in callback of async function: Error: [The data you sent was not accepted as valid]
    at [object Object].run (imports/plugins/included/shippo/server/methods/shippoapi.js:136:13)
    at ValidatedMethod._execute (packages/mdg:validated-method/validated-method.js:93:12)
    at [object Object].ValidatedMethod.connection.methods._connection$methods.(anonymous function) (packages/mdg:validated-method/validated-method.js:54:23)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:1686:15
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:1684:36
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1622:26)
    at ValidatedMethod.call (packages/mdg:validated-method/validated-method.js:67:30)
    at [object Object].shippoGetShippingRatesForCart (imports/plugins/included/shippo/server/methods/shippo.js:405:63)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
 => awaited here:
    at Promise.await (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1635:22)
    at ValidatedMethod.call (packages/mdg:validated-method/validated-method.js:67:30)
    at [object Object].shippoGetShippingRatesForCart (imports/plugins/included/shippo/server/methods/shippo.js:405:63)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:1686:15
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:1684:36
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1622:26)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1604:17)
    at getShippingRates (imports/plugins/included/shippo/server/hooks/rates.js:55:34)
    at server/api/hooks.js:54:14
 => awaited here:
    at Promise.await (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1635:22)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1604:17)
    at getShippingRates (imports/plugins/included/shippo/server/hooks/rates.js:55:34)
    at server/api/hooks.js:54:14
    at Array.reduce (native)
    at Object.Hooks.Events.run (server/api/hooks.js:53:22)
    at [object Object].shippingGetShippingRates (server/methods/core/shipping.js:81:18)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:1686:15
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:1684:36
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
 => awaited here:
    at Promise.await (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1635:22)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1604:17)
    at [object Object].shippingUpdateShipmentQuotes (server/methods/core/shipping.js:29:28)
    at packages/check.js:128:16
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at packages/ddp-server/livedata_server.js:1686:15
    at [object Object].EVp.withValue (packages/meteor.js:1134:15)
    at packages/ddp-server/livedata_server.js:1684:36
    at [object Object]._.extend.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1622:26)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1604:17)
    at server/methods/core/cart.js:413:14
    at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
 => awaited here:
    at Promise.await (/opt/reaction/dist/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at [object Object]._.extend.apply (packages/ddp-server/livedata_server.js:1635:22)
    at [object Object]._.extend.call (packages/ddp-server/livedata_server.js:1604:17)
    at server/methods/core/cart.js:413:14
    at wrappedCallbackForParsingMongoValidationErrors (packages/aldeed_collection2-core.js:511:15)
    at packages/mongo/collection.js:612:5
    at args.(anonymous function) (packages/matb33_collection-hooks.js:500:23)
    at runWithEnvironment (packages/meteor.js:1188:24)
    at packages/meteor.js:1201:14
    at packages/mongo/mongo_driver.js:319:7
    at packages/mongo/mongo_driver.js:606:15
    at runWithEnvironment (packages/meteor.js:1188:24)
```

**Comment by spencern** [comment]
Do we know if this was introduced in `1.4.3` or if it could have come in earlier?

**Comment by spencern** [comment]
Also, the startup output indicates version 1.4.4 here
```
15:26:32.915Z  INFO Reaction: Reaction Version: 1.4.4
```

**Comment by zenweasel** [comment]
Are the steps to reproduce just start the app without a `reaction.json` and you see this bug?

**Comment by zenweasel** [comment]
@aaronjudd Should we go ahead and close this or can get steps to reproduce?
