### ISSUE TITLE
Receive error in console when creating shop

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3008]
This is a pretty big blocker as I can no longer create a shop

### Expected behavior
No errors in server console

### Actual Behavior
Receive error in server console:
```
02:27:34.471Z ERROR Reaction: Failed to shop/createShop
  Error: Units of length is required
      at getErrorObject (packages/aldeed_collection2-core.js:480:15)
      at [object Object].doValidate (packages/aldeed_collection2-core.js:462:13)
      at [object Object].Mongo.Collection.(anonymous function) (packages/aldeed_collection2-core.js:214:25)
      at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/dispatch_run-as-user.js:325:19)
      at [object Object].shopCreateShop (server/methods/core/shop.js:111:37)
<snip>
```

### Steps to Reproduce the Behavior
1. Login as admin
1. Invite a shop owner
1. Observe error in the console.

### Versions
```
Node: 7.10.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.13.1
Reaction: 1.5.0
Reaction branch: wanja-fix-issue-2868
Docker: 17.06.2-ce
```

**Comment by zenweasel** [comment]
this appears to only happen on this branch and not `marketplace`
