### ISSUE TITLE
I dunno why its throwing this server connecting error??

### ISSUE THREAD

**Issue by oaulakh** [reactioncommerce/reaction#3211]
Can anyone understand why i am getting this error all the way in starting!
`boo (master *) reaction $ reaction --port 8080

Using settings file at settings/dev.settings.json

Setting up plugin imports...

Installing dependencies for connectors-shopify...

npm WARN reaction-connectors-shopify@1.0.0 No repository field.

up to date in 0.085s
Setting up style imports...

[[[[[ ~/code/test/reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
/home/boo/.meteor/packages/meteor-tool/.1.6.0.1whvdik.oongk++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Object prototype may only be an Object or null: undefined
    at Object.create (<anonymous>)
    at create (/home/boo/code/test/reaction/node_modules/babel-runtime/node_modules/core-js/library/fn/object/create.js:4:18)
    at exports.default (/home/boo/code/test/reaction/node_modules/babel-runtime/helpers/inherits.js:24:45)
    at /home/boo/code/test/reaction/.meteor/local/build/programs/server/app/app.js:10194:26
    at blazeLayout.js (imports/plugins/core/layout/lib/blazeLayout.js:57:4)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
    at router.js (imports/plugins/core/router/lib/router.js:1:1529)
    at fileEvaluate (packages/modules-runtime.js:333:9)
    at require (packages/modules-runtime.js:228:16)
=> Exited with code: 1
/home/boo/.meteor/packag`

**Comment by aaronjudd** [comment]
Looks like you updated to Meteor 1.6..  Closing in favor of #3207

**Comment by oaulakh** [comment]
http://paste.ubuntu.com/25860359/

this time run reaction without update, and its still throwing error!
