### ISSUE TITLE
Cannot checkout with merchant products with stripe

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#3248]
### Expected behavior

Should be able to checkout with a product from a merchant shop.

### Actual behavior

Cannot checkout with a product in the cart from a merchant shop.

Error received:

```
17:17:42.257Z ERROR Reaction: [Error processing payment for merchant with shopId ozm2hPY49EScFcbSm]
  Error: [Error processing payment for merchant with shopId ozm2hPY49EScFcbSm]
      at imports/plugins/included/payments-stripe/server/methods/stripe.js:328:19
      at Array.forEach (native)
      at [object Object]._callee$ (imports/plugins/included/payments-stripe/server/methods/stripe.js:292:15)
      at tryCatch (/Users/mikemurray/Projects/reaction/reaction/node_modules/regenerator-runtime/runtime.js:65:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/mikemurray/Projects/reaction/reaction/node_modules/regenerator-runtime/runtime.js:299:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/mikemurray/Projects/reaction/reaction/node_modules/regenerator-runtime/runtime.js:117:21)
      at step (/Users/mikemurray/Projects/reaction/reaction/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at /Users/mikemurray/Projects/reaction/reaction/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
      at new Promise (/Users/mikemurray/Projects/reaction/reaction/node_modules/core-js/library/modules/es6.promise.js:171:7)
      at [object Object].<anonymous> (/Users/mikemurray/Projects/reaction/reaction/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
      at [object Object].stripePaymentCreateCharges (imports/plugins/included/payments-stripe/server/methods/stripe.js:210:3)
      at packages/check.js:128:16
      at [object Object].EVp.withValue (packages/meteor.js:1134:15)
      at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
      at packages/ddp-server/livedata_server.js:719:19
```

### Steps to reproduce the behavior

1. Invite a shop owner
1. Accept invitation
1. As the marketplace owner set the shop to `active` under `Marketplace Shops` (globe icon in icon toolbar)
1. As a marketplace owner, add your shipping methods and enable stripe
1. As the shop owner of the merchant shop, add a product, make it visible, etc.
1. As an anonymous user, checkout with the product created by the merchant shop
1. Receive the error.

### Versions

Node: 7.2.0
NPM: 5.3.0
Meteor Node: 4.8.4
Meteor NPM: 4.6.1
Reaction CLI: 0.20.0
Reaction: 1.5.6
Reaction branch: master
Docker: 17.09.0-ce

**Comment by mikemurray** [comment]
Can checkout with a product from a merchant shop. Missed a setup phase where the merchant shop needs to open shop settings, enter their address, and connect with Stripe. Need to verify there is documentation for this.
