### ISSUE TITLE
  Error occurred while sending sms TypeError: Cannot read property 'profile' of undefined

### ISSUE THREAD

**Issue by aaronjudd** [reactioncommerce/reaction#3356]
Orders can complete, but are delayed while this error occurs.

```
23:46:32.639Z  WARN Reaction:
  Error: error occured while sending sms TypeError: Cannot read property 'profile' of undefined
      at DDPCommon.MethodInvocation.smsSend (imports/plugins/included/sms/server/methods/sms.js:52:30)
      at packages/check.js:128:16
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
      at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
      at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
      at resolve (packages/ddp-server/livedata_server.js:1684:36)
      at new Promise (<anonymous>)
      at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
      at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
      at Server.call (packages/ddp-server/livedata_server.js:1604:17)
      at DDPCommon.MethodInvocation.notificationSend (imports/plugins/included/notifications/server/methods/notifications.js:57:16)
      at packages/check.js:128:16
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
      at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
      at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
      at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1184:15)
      at Promise (packages/ddp-server/livedata_server.js:715:46)
```
### Steps to reproduce the behavior
Placed order with Shippo + PayPal Express + Stripe.  

Configured with rc-config, nothing done specifically to setup SMS.

Place an order as a user.
Login as admin to fullfill order, witness server console.

### Versions
```
Node: 6.11.1
NPM: 5.5.1
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.23.2
Reaction: 1.6.0
Reaction branch: meteor-1.6
Docker: 17.09.0-ce
```

**Comment by iakhator** [comment]
@aaronjudd ,  I can't seem to reproduce this error following the guidelines above. Maybe I am missing something.

**Comment by codejockie** [comment]
I think this issue is reproducible only when a user adds billing/shipping info without including a phone number. The error is trying to send an sms to an undefined phone book value.

**Comment by iakhator** [comment]
@codejockie , not at all.
