### ISSUE TITLE
Integration Test in server/lib breaks reaction test

### ISSUE THREAD

**Issue by ragboyjr** [reactioncommerce/reaction#3364]
I have plugin structure like:

```
imports/plugins/custom/coed-connectors-magneto2/
  /register.js
  /server/lib/import.app-test.js
```

When I run reaction test I get an error before any tests can run.

Here are the contents of `import.app-test.js`

```js
/* eslint dot-notation: 0 */
import { Meteor } from "meteor/meteor";
import { Reaction } from "/server/api";
import { expect } from "meteor/practicalmeteor:chai";
import Fixtures from "/server/imports/fixtures";

Fixtures();

describe.only('magento2 product import', () => {
    it('can get the reaction shop id', () => {
        console.log(Reaction.getShopId());
    })
});
```

I'm willing to help or submit a PR but have no clue on why this bug happens like this.

### Expected behavior

Running `reaction test` properly executes the test and exits.

### Actual behavior

```
=> Started proxy.                          
=> Started MongoDB.                        
W20171201-14:32:11.137(-8)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20171201-14:32:11.206(-8)? (STDERR) While this implementation will work correctly, it is known to be
W20171201-14:32:11.206(-8)? (STDERR) approximately three times slower than the native implementation.
W20171201-14:32:11.207(-8)? (STDERR) In order to use the native implementation instead, run
W20171201-14:32:11.207(-8)? (STDERR) 
W20171201-14:32:11.207(-8)? (STDERR)   meteor npm install --save bcrypt
W20171201-14:32:11.208(-8)? (STDERR) 
W20171201-14:32:11.208(-8)? (STDERR) in the root directory of your application.
W20171201-14:32:14.867(-8)? (STDERR) /Users/rjgarcia/.meteor/packages/meteor-tool/.1.6.0.1xsofn0++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20171201-14:32:14.868(-8)? (STDERR) 						throw(ex);
W20171201-14:32:14.868(-8)? (STDERR) 						^
W20171201-14:32:14.868(-8)? (STDERR) 
W20171201-14:32:14.869(-8)? (STDERR) TypeError: Cannot read property 'newContext' of undefined
W20171201-14:32:14.869(-8)? (STDERR)     at prop-types.js (lib/api/prop-types.js:11:31)
W20171201-14:32:14.869(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171201-14:32:14.869(-8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171201-14:32:14.869(-8)? (STDERR)     at index.js (lib/api/index.js:1:237)
W20171201-14:32:14.870(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171201-14:32:14.871(-8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171201-14:32:14.871(-8)? (STDERR)     at helpers.js (lib/collections/schemas/helpers.js:1:360)
W20171201-14:32:14.872(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20171201-14:32:14.872(-8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20171201-14:32:14.873(-8)? (STDERR)     at accounts.js (lib/collections/schemas/accounts.js:1:215)
=> Started your app.

=> App running at: http://localhost:3000/

Tests failed.
```

### Steps to reproduce the behavior

Create a plugin with a server/lib directory and place a *.app-test.js file in there and run `reaction test`

### Versions

```
Node: 8.9.1
NPM: 5.5.1
Meteor Node: 8.8.1
Meteor NPM: 5.4.2
Reaction CLI: 0.24.2
Docker: 17.09.0-ce
```

**Comment by zenweasel** [comment]
I think putting a `lib` directory is confusing Meteor. `lib`  directories are loaded first before `server and client` (even though it's in a `server` directory. You can see more about that [here](https://guide.meteor.com/structure.html).

Moving this up into the `import/plugins/custom/myplugin/server` made the error go away.

**Comment by ragboyjr** [comment]
@zenweasel dude. You freaking rock!

Thank you so much :). I'll keep that in mind when I create my dir structures.

**Comment by ragboyjr** [comment]
We can close this then, hopefully it helps someone else out if they stumble across this.
