### ISSUE TITLE
BrowserPolicy is not defined

### ISSUE THREAD

**Issue by leemm** [reactioncommerce/reaction#346]
Hi,

Just done a fresh clone following the installation and the app won't start due to this:

```
W20150316-18:15:08.932(0)? (STDERR) ReferenceError: BrowserPolicy is not defined
W20150316-18:15:08.932(0)? (STDERR)     at server/policy.coffee:1:1
W20150316-18:15:08.932(0)? (STDERR)     at server/policy.coffee:1:1
W20150316-18:15:08.932(0)? (STDERR)     at /reaction/.meteor/local/build/programs/server/boot.js:205:10
```

For the time being I've just removed the offending lines from the file and the app starts fine.  But now results in:

```
I20150316-18:18:04.177(0)? Exception from sub 4B2ES4pwLCKYWmSLu Error: Did not check() all arguments during publisher 'Sessions'
I20150316-18:18:04.177(0)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150316-18:18:04.177(0)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150316-18:18:04.178(0)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1596:1)
```

Any idea where to start debugging?

Thanks.

**Comment by Gouthamve** [comment]
Try meteor remove ```meteor remove audit-argument-checks```

Also clone the ```reaction-core```  and ```reaction-core-theme``` repo into the packages directory. I am sure you need not remove the offending lines if you cloned.

**Comment by leemm** [comment]
That's done it.  Thanks a lot.
