### ISSUE TITLE
check fails on updateWorkFlow

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#360]
While updating the order on the backend, this error shows up the terminal
```
I20150408-23:44:35.238(5.5)? Exception while invoking method 'updateWorkflow' Error: Match error: Expected string, got undefined
I20150408-23:44:35.239(5.5)?     at checkSubtree (packages/check/match.js:159:1)
I20150408-23:44:35.239(5.5)?     at check (packages/check/match.js:32:1)
I20150408-23:44:35.240(5.5)?     at [object Object].Meteor.methods.updateHistory (packages/reactioncommerce:core/server/methods/orders/orders.coffee:51:5)
I20150408-23:44:35.240(5.5)?     at packages/check/match.js:109:1
I20150408-23:44:35.240(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150408-23:44:35.241(5.5)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150408-23:44:35.241(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150408-23:44:35.241(5.5)?     at packages/ddp/livedata_server.js:1530:1
I20150408-23:44:35.241(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150408-23:44:35.242(5.5)?     at [object Object]._.extend.apply (packages/ddp/livedata_server.js:1529:1)
I20150408-23:44:35.242(5.5)? Sanitized and reported to the client as: Match failed [400]
I20150408-23:44:35.242(5.5)? 
```

**Comment by aaronjudd** [comment]
Closed https://github.com/reactioncommerce/reaction-core/pull/122
