### ISSUE TITLE
Should update release-1.8.0/package-lock.json to reflect new braintree version 2.7.0

### ISSUE THREAD

**Issue by prinzdezibel** [reactioncommerce/reaction#3786]
Checking out with Braintree causes a server side error in release-1.8.0, because in package-lock.json [braintree bindings](https://github.com/braintree/braintree_node) are pinned to 2.6.0, which is incompatible with the current code base. The package is pinned to 2.7.0 in package.json of branch release-1.8.0.

### Expected behavior
Checkout with braintree should work without error

### Actual behavior

A server side error is thrown:
```
ERROR Reaction: Maximum call stack size exceeded
  RangeError: Maximum call stack size exceeded
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
      at Object.EJSON.clone.v [as clone] (packages/ejson/ejson.js:594:18)
      at Object.keys.forEach.key (packages/ejson/ejson.js:595:22)
      at Array.forEach (<anonymous>)
```

### Steps to reproduce the behavior
- As an admin, enable braintree
- As a user put an item to cart and checkout
- After entering the credentials, a server side error occurs.

### Analysis
The failure in braintree 2.6.0 happens because the paymentSubmit API call returns an result object with a circular reference (BraintreeGateway). This causes EJSON serialization to fail:
```
EJSON.stringify(paymentSubmitResult)

ejson.js:594 Uncaught RangeError: Maximum call stack size exceeded
  [.. much more repetitive output ..]
```

### Versions
Node: 8.2.1
NPM: 5.3.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.26.4
Reaction: 1.8.0
Reaction branch: release-1.8.0
Docker: 17.03.1-ce

**Comment by zenweasel** [comment]
I'm confused how this happened because I specifically tested the Braintree checkout when we upgraded the library. The only thing I can think of was that I accidentally reset my package.json at one point and did an ncu to get the changes back and somehow the library was updated again during that two hour time frame? Ugh

**Comment by zenweasel** [comment]
I tested this on the node dependency branch `refactor-3029-spencern-review-update-npm-deps` and not seeing the error. The version is pinned to 2.7.0 as it is on the `release-1.80` branch.

**Comment by zenweasel** [comment]
I'm also not seeing this error on the `release-1.8.0` branch.

**Comment by prinzdezibel** [comment]
it's pinned 2.6.0 (works not) in package-lock.json, but 2.4.0 (works) in package.json.  

what happens if you delete node_modules/braintree and install again?

**Comment by zenweasel** [comment]
I always do that every time I test it

**Comment by zenweasel** [comment]
I don't see any of those references to 2.6 you are talking about. Can you double check you are up to date with master?

**Comment by zenweasel** [comment]
Maybe this is the problem, looks like there might be discrenpency betwee package.json and package-lock.json
```
 »» cat package.json | grep -i braintree
    "braintree": "^2.7.0",

[brenthoover@sloat: 17:58:31 ~/Projects/js/reaction  (release-1.8.0 $) - [1153]
 »» cat package-lock.json | grep -i braintree
    "@braintree/wrap-promise": {
      "resolved": "https://registry.npmjs.org/@braintree/wrap-promise/-/wrap-promise-1.1.1.tgz",
    "braintree": {
      "resolved": "https://registry.npmjs.org/braintree/-/braintree-2.6.0.tgz",
        "@braintree/wrap-promise": "1.1.1",
```

**Comment by prinzdezibel** [comment]
weird.
these are from my branch:

https://github.com/reactioncommerce/reaction/blob/fix-3778-error-on-adding-address/package.json
https://github.com/reactioncommerce/reaction/blob/fix-3778-error-on-adding-address/package-lock.json

and those from release-1.8.0:
https://github.com/reactioncommerce/reaction/blob/release-1.8.0/package.json
https://github.com/reactioncommerce/reaction/blob/release-1.8.0/package-lock.json

I'm going to merge release-1.8.0 in my branch again and see what happens.

**Comment by prinzdezibel** [comment]
I pulled package.json from release-1.8.0 again. `npm install` did update package-lock.json to braintree 2.7.0 (and others as well). 

It seems that we need to update 
https://github.com/reactioncommerce/reaction/blob/release-1.8.0/package-lock.json.

**Comment by zenweasel** [comment]
Yeah, this was my mistake when I updated the npm package I didn't commit the package-lock.json

**Comment by zenweasel** [comment]
@prinzdezibel Can we close this now? Didn't you essentially fix this in your moment PR or do we still need this?

**Comment by prinzdezibel** [comment]
@zenweasel No, my PR doesn't fix it. Merging in release-1.8.0 just pinned braintree to 2.7.0 in package.json. But it still is pinned as 2.6.0 in package-lock.json.

This leads to changed package-lock.json in working copy whenever braintree is not matched and gets updated.

**Comment by zenweasel** [comment]
Right. Submitted a PR

**Comment by zenweasel** [comment]
Fixed via upstream changes (any update to `package.json` should have triggered this). Braintree is now 2.7.0 in `package-lock.json`. Closing.
