### ISSUE TITLE
Error when enabling Shopify inventory hooks

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#3974]
## Issue Description
Receive "Error setting up Shopify Sync" in browser and error in server console when enabling shopify inventory sync

## Steps to Reproduce
1. Login as admin
1. Go to "Connectors" panel
1. Select "Update Inventory when new Shopify order is placed"
1. Click on "Setup Sync"
1. Observe errors in server and browser

```
  server-error Shopify API Error creating new webhook: Response code 422 (Unprocessable Entity) { HTTPError: Response code 422 (Unprocessable Entity)
      at stream.catch.then.data (/Users/brenthoover/Projects/js/reaction/node_modules/got/index.js:341:13)
      at /Users/brenthoover/.meteor/packages/promise/.0.10.1.trxnxh.msck++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/Users/brenthoover/.meteor/packages/promise/.0.10.1.trxnxh.msck++os+web.browser+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/plugins/included/connectors-shopify/server/methods/webhooks/webhooks.js:55:13)
```

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.28.0
Reaction: 1.9.0
Reaction branch: release-1.9.0
Docker: 17.12.0-ce

```

**Comment by zenweasel** [comment]
This is not a regression as it happens in `master`/`1.8.2` as well

**Comment by Akarshit** [comment]
This happens if you try to setup the sync again on the same address. 
We see this because we keep resetting our databases which removes the history of webhook locally, but still use the same URL to pipe to localhost.
The acutal error is 
`address: [The address has already been taken]`

Should we do something about this?

**Comment by zenweasel** [comment]
Does the API allow you to reset and then set the webhooks?

**Comment by zenweasel** [comment]
I agree with the change in impact status, but in the future try to put a note like "bumping down from major to minor because it only affects you when trying to set the hooks multiple times".

**Comment by Akarshit** [comment]
@zenweasel Why would we want to delete the webhook and then recreate the webhook with the same callback address?

**Comment by zenweasel** [comment]
Because it would make this idempotent.

**Comment by Akarshit** [comment]
To delete a webhook we need the Shopify's Id of the webhook. This `id` is stored in the database. But if we are able to get the `id` of the webhook, that means the webhook data was already present in the database and the control would never reach where new webhook is created.

**Comment by zenweasel** [comment]
So do we need to query to see if there is already an existing webhook and get that data?

**Comment by Akarshit** [comment]
We will have to make a request to get all the webhooks subscription for the shop. Then we can check if  those already contain the webhooks we are trying to make and skip the creation accordingly.

**Comment by zenweasel** [comment]
That seems like a solid plan
