### ISSUE TITLE
Error in console with devtools small dataset and catalog

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4014]
## Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description

When using the small products are published with the [DevTools](https://github.com/reactioncommerce/reaction-devtools) the following error happens

```23:22:04.573Z ERROR Reaction: After applying the update to the document {_id: "cxYA8s8qdi8qnYSNw", ...}, the (immutable) field '_id' was found to have been altered to _id: "GpZM5v5qQBCdXsoqW"
  MinimongoError: After applying the update to the document {_id: "cxYA8s8qdi8qnYSNw", ...}, the (immutable) field '_id' was found to have been altered to _id: "GpZM5v5qQBCdXsoqW"
      at MinimongoError (packages/minimongo/common.js:1087:17)
      at Function.LocalCollection._modify (packages/minimongo/local_collection.js:1169:13)
      at Function.LocalCollection._createUpsertDocument (packages/minimongo/local_collection.js:935:19)
      at MongoConnection._update (packages/mongo/mongo_driver.js:535:38)
      at MongoConnection.<anonymous> (packages/meteor.js:258:21)
      at MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:743:49)
      at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks.js:133:23)
      at ns.Collection.update (packages/mongo/collection.js:580:31)
      at ns.Collection.Mongo.Collection.(anonymous function) (packages/aldeed:collection2/collection2.js:213:19)
      at ns.Collection.Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user.js:325:19)
      at ns.Collection.upsert (packages/mongo/collection.js:647:17)
      at packages/matb33_collection-hooks.js:710:21
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
      at Object.directOp (packages/matb33_collection-hooks.js:47:27)
      at ns.Collection.<anonymous> (packages/matb33_collection-hooks.js:709:31)
      at ns.Collection.collection.(anonymous function) [as upsert] (packages/matb33_collection-hooks.js:146:21)
      at Promise.asyncApply (imports/plugins/core/catalog/server/methods/catalog.js:123:36)
      at /Users/mikemurray/.meteor/packages/promise/.0.10.2.5jscv1.rys4g++os+web.browser+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

## Steps to Reproduce

1. Checkout master
1. Follow [DevTools](https://github.com/reactioncommerce/reaction-devtools) the following error happens instructions to set up
1. Start app
1. Sign in as admin
1. Open dev tools
1. Reset data
1. Load Products and Tags from the small dataset
1. See the error in terminal

## Possible Solution

Remove `_id` from the catalog update object. The `upsert` should take care of the id of the document for is anyway.

```
product.productId = product._id
delete `product._id`
```

### Versions
Node: 7.2.0
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.9.0
Reaction branch: master
Docker: 17.12.0-ce

**Comment by aldeed** [comment]
I have not seen this lately but we can reopen if others are still seeing it.
