### ISSUE TITLE
Receive server error when trying to save settings

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4016]
## Issue Description
When savings the Stripe settings I get the following error in the server console:
```
Exception while invoking method '/Packages/update' Error: Match error: Expected string, got undefined
    at check (packages/check/match.js:35:15)
    at Object.getUserShopId (server/api/core/core.js:444:5)
    at Object.allow (server/startup/collection-security.js:50:33)
    at _.every.restriction (packages/ongoworks:security/lib/server/Security.Rule.js:84:37)
    at Array.every (<anonymous>)
    at Function._.every._.all (packages/underscore.js:253:62)
    at Security.Rule.js.Security.Rule.allow (packages/ongoworks:security/lib/server/Security.Rule.js:61:14)
    at _.any.rule (packages/ongoworks:security/lib/server/Security.Check.js:91:38)
    at Array.some (<anonymous>)
    at Function._.some._.any (packages/underscore.js:267:59)
    at Security.Check.js.Security.Check.check (packages/ongoworks:security/lib/server/Security.Check.js:91:14)
    at packages/ongoworks:security/lib/server/Security.Rule.js:105:66
    at self._validators.update.deny.some.validator (packages/allow-deny/allow-deny.js:330:12)
    at Array.some (<anonymous>)
    at ns.Collection.CollectionPrototype._validatedUpdate (packages/allow-deny/allow-deny.js:328:36)
    at MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
    at packages/check/match.js:108:16
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: Match failed [400]
```

## Steps to Reproduce
1. Load app
1. Go to Payment settings
1. Enable Stripe
1. Click on "Save Settings"
1. Observe errors

## Possible Solution
Probably related to the caching of ShopId

### Versions
(run `reaction -v` from your reaction directory)

**Comment by zenweasel** [comment]
Update: Get this match error when updating many settings such as change the base unit of measure.

**Comment by zenweasel** [comment]
Cannot create a shop because you can't save those settings so marketplace is essentially broken
