### ISSUE TITLE
Error in console and incorrect display when using Dollar discounts

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4078]
## Issue Description
When using the "Codes" discount and selecting the type as "dollar", if you process an order you get an error on the server side and the wrong display in the completed order page

Error:

```
  TypeError: Cannot read property 'subtotal' of undefined
      at MethodInvocation.orders/sendNotification (server/methods/core/orders.js:697:59)
      at packages/check/match.js:108:16
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
      at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
      at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
      at resolve (packages/ddp-server/livedata_server.js:1684:36)
      at new Promise (<anonymous>)
      at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
      at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
      at Server.call (packages/ddp-server/livedata_server.js:1604:17)
      at MethodInvocation.copyCartToOrder (server/methods/core/cartToOrder.js:204:14)
      at MethodInvocation.MethodHooks._wrappers.(anonymous function) (server/api/method-hooks.js:106:70)
      at packages/check/match.js:108:16
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
      at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
      at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1686:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
      at resolve (packages/ddp-server/livedata_server.js:1684:36)
      at new Promise (<anonymous>)
      at Server.applyAsync (packages/ddp-server/livedata_server.js:1683:12)
      at Server.apply (packages/ddp-server/livedata_server.js:1622:26)
      at Server.call (packages/ddp-server/livedata_server.js:1604:17)
      at MethodInvocation.MethodHooks.after.options (server/methods/core/hooks/cart.js:31:32)
      at _each (server/api/method-hooks.js:114:36)
      at arrayEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/_arrayEach.js:15:9)
      at forEach (/Users/brenthoover/Projects/js/reaction/node_modules/lodash/forEach.js:38:10)
      at MethodInvocation.MethodHooks._wrappers.(anonymous function) (server/api/method-hooks.js:113:5)
      at packages/check/match.js:108:16
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
      at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:107:41)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1765:18)
```

![2018-03-28_10-37-51](https://user-images.githubusercontent.com/72819/38005638-24d1239c-3274-11e8-93f6-7128c8e44302.png)

The promotional code here was called "DOLLAROFF" which is what should be displayed here, not the payment type which is what `code` is.

## Steps to Reproduce
1. Login as admin
1. Go the Payments/Codes dashboard
1. Add a new discount code with the discount method "credit" and the code to be "DOLLAROFF" and the amount to 1.
1. Add to cart and apply this discount when checking out
1. Observe this error on the server-side
1. Observe the incorrect display on the completed order page

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.10.0
Reaction branch: master
Docker: 18.03.0-ce
```

**Comment by aldeed** [comment]
Refers to older UI
