### ISSUE TITLE
Receive error in server console when placing an order

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4157]
## Issue Description
Receive the following error in the server console when placing an order
```
06:50:30.725Z ERROR Reaction: Error in orders/sendNotification for order Mw9LLqsGkm2N6vrrq
  Error: Can't wait without a fiber
      at Function.wait (/Users/brenthoover/.meteor/packages/meteor-tool/.1.6.1.xbgv5v.yxdmr++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:159:9)
      at Future.wait (/Users/brenthoover/.meteor/packages/meteor-tool/.1.6.1.xbgv5v.yxdmr++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:448:10)
      at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1018:47)
      at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1052:22)
      at SynchronousCursor.map (packages/mongo/mongo_driver.js:1062:10)
      at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1086:17)
      at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:876:44)
      at MongoConnection.findOne (packages/mongo/mongo_driver.js:783:56)
      at Collection.findOne (packages/mongo/collection.js:351:29)
      at /Users/brenthoover/Projects/js/reaction/node_modules/@reactioncommerce/file-collections/dist/node/MeteorFileCollection.js:145:40
      at new Promise (<anonymous>)
<snip>
```

## Steps to Reproduce
1. Configure shipping and payment method (I tested Stripe and Braintree)
1. Add a product to cart and checkout
1. Observe error in server console
1. Observe confirmation email is never sent

**Note:** Akarshit is not seeing this error so it would be helpful for someone to reproduce this

### Versions
```
Node: 8.9.4
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.11.0
Reaction branch: release-1.11.0
Docker: 18.03.0-ce
```

**Comment by srindom** [comment]
I am receiving the same error on the master branch.

```
Exception while invoking method 'orders/sendNotification' Error: Can't wait without a fiber
    at Function.wait (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1.12f1ind.5xzd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:159:9)
    at Future.wait (/home/ubuntu/.meteor/packages/meteor-tool/.1.6.1.12f1ind.5xzd++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:448:10)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1018:47)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1052:22)
    at SynchronousCursor.map (packages/mongo/mongo_driver.js:1062:10)
    at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1086:17)
    at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:876:44)
    at MongoConnection.findOne (packages/mongo/mongo_driver.js:783:56)
    at Collection.findOne (packages/mongo/collection.js:351:29)
    at /home/ubuntu/tekla/reaction/node_modules/@reactioncommerce/file-collections/dist/node/MeteorFileCollection.js:145:40
    at new Promise (<anonymous>)
```

# Versions

```
Node: 8.11.1
NPM: 5.6.0
Meteor Node: 8.9.4
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.11.0
Reaction branch: master
```

**Comment by ajporlante** [comment]
Closing this as I'm unable to replicate this in `v1.13.0`.
