### ISSUE TITLE
Apply meteor patch 1.6.1.1

### ISSUE THREAD

**Issue by mostlyjason** [reactioncommerce/reaction#4241]
## Issue Description
Getting an error message after running reaction with meteor 1.6.1:
```
13:20:40.607Z ERROR Reaction: Can't wait without a fiber
  Error: Can't wait without a fiber
      at Function.wait (/home/jason/.meteor/packages/meteor-tool/.1.6.1.1l85fxu.vlg7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:159:9)
      at Future.wait (/home/jason/.meteor/packages/meteor-tool/.1.6.1.1l85fxu.vlg7++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:448:10)
      at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:1018:47)
      at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1052:22)
      at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:876:44)
      at Object.getVariants (imports/plugins/core/revisions/server/hooks.js:151:8)
      at Object.getVariantQuantity (imports/plugins/core/revisions/server/hooks.js:167:26)
      at variants.every.variant (imports/plugins/core/catalog/server/methods/catalog.js:18:22)
      at Array.every (<anonymous>)
      at isSoldOut (imports/plugins/core/catalog/server/methods/catalog.js:16:19)
      at publishProductToCatalog (imports/plugins/core/catalog/server/methods/catalog.js:112:23)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

## Possible Solution
After applying patch 1.6.1.1 it works
meteor update --patch
Also required updating babel/runtime
meteor npm install --save @babel/runtime

### Versions
Node: 8.11.1
NPM: 5.6.0
Meteor Node: 8.11.1
Meteor NPM: 5.6.0
Reaction CLI: 0.29.0
Reaction: 1.11.0
Reaction branch: master
Docker: 18.03.0-ce

**Comment by zenweasel** [comment]
@mostlyjason It looks from your traceback that you are already running 1.6.1.1 which is probably causing your error. We don't have any immediate plans to update to 1.6.1.1 (we will probably move directly to 1.7) but if you wanted to put in a PR for it we could consider it.
