### ISSUE TITLE
Error: EPERM: operation not permitted,

### ISSUE THREAD

**Issue by kinivi** [reactioncommerce/reaction#4280]
## Prerequisites
*  Are you running the latest version? YES
*  Are you able to consistently reproduce the issue? YES
*  Did you search the issue queue for existing issue? NO same issues 

## Issue Description
Hello, i m bew in reaction commerce. So i want to install it from instruction, but thre is an error after trying running it.

`Error: EPERM: operation not permitted, stat 'C:\projects\my-reaction-projects\reaction\.meteor\local\build\programs\server\node_modules'
    at Object.realpathSync (fs.js:1670:17)
    at toRealPath (module.js:158:13)
    at tryFile (module.js:154:22)
    at tryExtensions (module.js:166:22)
    at Function.Module._findPath (module.js:219:20)
    at Function.Module._resolveFilename (module.js:536:25)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.require (C:\projects\my-reaction-projects\reaction\.meteor\local\build\programs\server\boot.js:284:20)`

And after that is infinity loop

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. creating reaction project
2. `reaction run`
3. enjoy error

### Versions
latest

**Comment by zenweasel** [comment]
It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).
