### ISSUE TITLE
Console error on the server when placing an order with a discount

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4459]
## Issue Description
When placing an order with a discount you receive an error in the server console. The order seems to complete. I thought this was related to removing `discount-rates` but it's happening on `release-1.14.0` as well.

```
  TypeError: Cannot read property 'subtotal' of undefined
      at MethodInvocation.sendNotification (imports/plugins/core/orders/server/methods/sendNotification.js:115:57)
      at currentArgumentChecker.withValue (packages/check/match.js:118:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
      at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1764:18)
      at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1685:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
      at resolve (packages/ddp-server/livedata_server.js:1683:36)
      at new Promise (<anonymous>)
      at Server.applyAsync (packages/ddp-server/livedata_server.js:1682:12)
      at Server.apply (packages/ddp-server/livedata_server.js:1621:26)
      at Server.call (packages/ddp-server/livedata_server.js:1603:17)
      at MethodInvocation.copyCartToOrder (imports/plugins/core/cart/server/methods/copyCartToOrder.js:201:14)
      at MethodInvocation.MethodHooks._wrappers.(anonymous function) (imports/plugins/core/core/server/method-hooks.js:103:70)
      at currentArgumentChecker.withValue (packages/check/match.js:118:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
```

## Steps to Reproduce
1. Enable Shipping and Payment
1. Add a "DollarOff" discount code that is a dollar off (e.g. credit)
1. Place an order
1. Observe an error in the console

### Versions
`release-1.14.0`
I didn't test if this is happening on `master` yet

**Comment by aldeed** [comment]
Fixed
