### ISSUE TITLE
Error when trying to checkout with example payment provider

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#4465]
## Issue Description

Attempting to checkout with the example payment provider causes an error

```
Exception while invoking method 'cart/submitPayment' TypeError: moment is not a function
    at buildOrderSearchRecord (imports/plugins/included/search-mongo/server/methods/searchcollections.js:279:37)
    at Hooks.Events.add.doc (imports/plugins/included/search-mongo/server/hooks/search.js:40:5)
    at /Users/mikemurray/Projects/reaction/_cleanroom/reaction-4412/node_modules/@reactioncommerce/hooks/dist/main.js:71:14
    at Array.reduce (<anonymous>)
    at Object.Hooks.Events.run (/Users/mikemurray/Projects/reaction/_cleanroom/reaction-4412/node_modules/@reactioncommerce/hooks/dist/main.js:70:22)
    at MethodInvocation.copyCartToOrder (imports/plugins/core/cart/server/methods/copyCartToOrder.js:168:16)
    at MethodInvocation.MethodHooks._wrappers.(anonymous function) (imports/plugins/core/core/server/method-hooks.js:103:70)
    at currentArgumentChecker.withValue (packages/check/match.js:118:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1764:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1685:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
    at resolve (packages/ddp-server/livedata_server.js:1683:36)
    at new Promise (<anonymous>)
    at Server.applyAsync (packages/ddp-server/livedata_server.js:1682:12)
```

## Steps to Reproduce

1. Enable the `Example Payment` provider
2. Ensure a shipping provider is set
3. Sign in as a guest
4. Attempt to checkout

### Versions

Node: 10.7.0
NPM: 6.1.0
Meteor Node: 8.11.3
Meteor NPM: 5.10.0
Reaction CLI: 0.29.0
Reaction: 1.14.0
Reaction branch: feat-4355-aldeed-create-cart-mutation
Docker: 18.03.1-ce

**Comment by mikemurray** [comment]
Seems to be fine in `release-1.14.0` and `feat-4355-aldeed-create-cart-mutation`.
