### ISSUE TITLE
Error in server console when checking out on Release 1.14

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4482]
## Issue Description
Receive the following error in the server console
```
  Error merging cart for session 4i2JFjxYQTm43TnWf into new account cart 4bJzn73KpbbukGind { Error: No cart found with token 4i2JFjxYQTm43TnWf [not-found]
      at MethodInvocation.mergeCart (imports/plugins/core/cart/server/methods/mergeCart.js:60:11)
      at currentArgumentChecker.withValue (packages/check/match.js:118:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
      at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
      at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1764:18)
      at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:1685:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
      at resolve (packages/ddp-server/livedata_server.js:1683:36)
      at new Promise (<anonymous>)
      at Server.applyAsync (packages/ddp-server/livedata_server.js:1682:12)
      at Server.apply (packages/ddp-server/livedata_server.js:1621:26)
      at Server.call (packages/ddp-server/livedata_server.js:1603:17)
      at MethodInvocation.createCartMethod (imports/plugins/core/cart/server/methods/createCart.js:45:12)
      at currentArgumentChecker.withValue (packages/check/match.js:118:15)
      at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
      at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    isClientSafe: true,
    error: 'not-found',
    reason: 'No cart found with token 4i2JFjxYQTm43TnWf',
    details: undefined,
    message: 'No cart found with token 4i2JFjxYQTm43TnWf [not-found]',
    errorType: 'Meteor.Error' }
```

## Steps to Reproduce
1. Enable flat rates and example payment
1. Checkout as admin (not sure if it's relevant)
1. Observe error in console

### Versions
`release-1.14.0`

**Comment by spencern** [comment]
@zenweasel is this happening on an upgraded shop or a fresh shop. @aldeed did some work to update the way anonymous carts are handled in the recent GraphQL cart updates, and I'm wondering if this could be a migration issue.

**Comment by zenweasel** [comment]
@spencern After a full reset. I discovered it testing a PR and confirmed it's happening on `release-1.14.0`

**Comment by zenweasel** [comment]
fwiw it happens right when you do "Submit Payment", the "Your cart is empty" screen flashes for a second but the order completes.

**Comment by spencern** [comment]
I'm seeing this as well. 
The error is getting logged here: 
https://github.com/reactioncommerce/reaction/blob/release-1.14.0/imports/plugins/core/cart/server/methods/createCart.js#L46

There's a comment a few lines above `Do this async because we don't need the client to know if it failed`

**Comment by spencern** [comment]
Additionally, not 100% related to this error, but I see that on login, carts are no longer merging. Seems to be because of this change here: https://github.com/reactioncommerce/reaction/pull/4443/files#diff-396a353e751e20f50ac5654d69e700d5L237

**Comment by kieckhafer** [comment]
I saw this error on my first order, but don't see it on subsequent orders.

**Comment by aldeed** [comment]
I'm making some additional changes to how the merging works now, so I'll make sure this is resolved.
