### ISSUE TITLE
Removing last item from cart as anonymous user causes server console error

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4567]
## Issue Description
If you remove the last item from your cart so that it's completely empty you receive the following error in the server console and the cart component is not updated.
```
Exception while invoking method 'cart/removeFromCart' TypeError: Cannot read property 'userId' of null
    at MethodInvocation.removeFromCart (imports/plugins/core/cart/server/methods/removeFromCart.js:51:73)
    at currentArgumentChecker.withValue (packages/check/match.js:118:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1764:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1189:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

![2018-08-23_10-39-55](https://user-images.githubusercontent.com/72819/44501696-e4f51a00-a6c0-11e8-9e3b-e1405cf23a41.png)

## Steps to Reproduce
1. Add an item to cart as an anonymous user
1. Remove all items from cart
1. Observe the error in the console

### Versions
Reaction: `release-1.15.0`

**Comment by aldeed** [comment]
Looks to be a quick fix. On the `getGraphQLContextInMeteorMethod` line, it should use the same block of code that's used elsewhere:

```js
// In Meteor app we always have a user, but it may have "anonymous" role, meaning
  // it was auto-created as a kind of session.
  const userId = Meteor.userId();
  const anonymousUser = Roles.userIsInRole(userId, "anonymous", shopId);
  const userIdForContext = anonymousUser ? null : userId;

  const context = Promise.await(getGraphQLContextInMeteorMethod(userIdForContext));
```

The three lines for getting `userIdForContext` are the same everywhere, so they could be moved to a util function, which would just need shopId for the permission check.
