### ISSUE TITLE
App failed to start 

### ISSUE THREAD

**Issue by Azambadar** [reactioncommerce/reaction#4594]
I'm trying to run app since last week and have done all troubleshooting but no scucesss. Terminal is giving me this output but I can't figure out. 

C:\Users\iClick Digital\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^

Error: EPERM: operation not permitted, open 'C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\.meteor\local\resolver-result-cache.json'
 => awaited here:
    at Promise.await (C:\Users\iClick Digital\AppData\Local\.meteor\packages\meteor-tool\1.7.0_5\mt-os.windows.x86_64\dev_bundle\lib\node_modules\meteor-promise\promise_server.js:60:12)
    at copyFileHelper (C:\tools\fs\files.js:650:3)
    at Object.files.cp_r (C:\tools\fs\files.js:524:7)
    at Object.files.rename (C:\tools\fs\files.js:1799:13)
    at Object.writeFileAtomically (C:\tools\fs\files.js:1070:11)
    at ProjectContext._saveResolverResultCache (C:\tools\project-context.js:615:11)
    at C:\tools\project-context.js:590:14
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:525:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._resolveConstraints (C:\tools\project-context.js:524:13)
    at C:\tools\project-context.js:296:9
    at C:\tools\utils\buildmessage.js:359:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:286:18)
    at Profile.run (C:\tools\project-context.js:256:12)
    at Function.run (C:\tools\tool-env\profile.js:490:12)
    at ProjectContext.resolveConstraints (C:\tools\project-context.js:255:13)
    at C:\tools\runners\run-all.js:75:27
    at C:\tools\utils\buildmessage.js:271:13
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at exports.EnvironmentVariable.withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at new Runner (C:\tools\runners\run-all.js:74:18)
    at Object.exports.run (C:\tools\runners\run-all.js:366:16)
    at Command.doRunCommand [as func] (C:\tools\cli\commands.js:415:17)
    at C:\tools\cli\main.js:1531:15
{ Error: Command failed: meteor --raw-logs
    at checkExecSyncError (child_process.js:596:11)
    at execSync (child_process.js:633:13)
    at _callee$ (C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:72:43)
    at tryCatch (C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:65:40)
    at Generator.invoke [as _invoke] (C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\regenerator-runtime\runtime.js:117:21)
    at step (C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:98:191)
    at C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\dist\commands\run.js:98:361
    at run (C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\core-js\modules\es6.promise.js:75:22)
    at C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\core-js\modules\es6.promise.js:92:30
    at flush (C:\Users\iClick Digital\AppData\Roaming\npm\node_modules\reaction-cli\node_modules\core-js\modules\_microtask.js:18:9)
    at process._tickCallback (internal/process/next_tick.js:172:11)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18676,
  stdout: null,
  stderr: null }

Error: App failed to start

**Comment by zenweasel** [comment]
@Azambadar Looks like you have a permissions problem in your local system

It appears this is not an issue with Reaction but an issue with your particular installation. We would be glad to help you troubleshoot this problem further via our [chat channel](https://gitter.im/reactioncommerce/reaction) where we can continue the conversation in real time or via our [forums](https://forums.reactioncommerce.com).
