### ISSUE TITLE
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect

### ISSUE THREAD

**Issue by Azambadar** [reactioncommerce/reaction#4595]
Would like to bring this issue to your attention 
Setting up plugin imports...

Setting up style imports...

Provisioning assets...

[[[[[ C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction ]]]]]

=> Started proxy.
=> Started MongoDB.
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
10:55:27.683Z  WARN Reaction: No shop matching domain 'null'. Defaulting to Primary Shop.

C:\Users\iClick Digital\AppData\Local\.meteor\packages\promise\0.11.1\npm\node_modules\meteor-promise\promise_server.js:218
      throw error;
      ^
GraphQLError: Syntax Error GraphQL request (1:1) Unexpected String "The fields by which you are allowed to sort any query that returns an `AccountConnection`"

1: "The fields by which you are allowed to sort any query that returns an `AccountConnection`"
   ^
2: enum AccountSortByField {

    at syntaxError (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql\error\syntaxError.js:28:15)
    at unexpected (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql\language\parser.js:989:33)
    at parseDefinition (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql\language\parser.js:152:9)
    at parseDocument (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql\language\parser.js:106:22)
    at Object.parse (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql\language\parser.js:43:10)
    at buildSchemaFromTypeDefinitions (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql-tools\dist\schemaGenerator.js:132:33)
    at _generateSchema (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql-tools\dist\schemaGenerator.js:54:18)
    at makeExecutableSchema (C:\Users\iClick Digital\Documents\ZerotoMastery\frontendprojects\reaction\node_modules\graphql-tools\dist\schemaGenerator.js:70:20)
    at schema.js (imports/plugins/core/graphql/server/no-meteor/schema.js:4:16)
    at fileEvaluate (packages\modules-runtime.js:339:7)
    at require (packages\modules-runtime.js:238:16)
    at createApolloServer.js (imports/plugins/core/graphql/server/no-meteor/createApolloServer.js:1:853)
    at fileEvaluate (packages\modules-runtime.js:339:7)
    at require (packages\modules-runtime.js:238:16)
    at index.js (imports/plugins/core/graphql/server/index.js:1:390)
    at fileEvaluate (packages\modules-runtime.js:339:7)
=> Exited with code: 1
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/client/plugins.less.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
   Building the application                  -

**Comment by aldeed** [comment]
Some time ago I tried various things to get rid of these warnings but nothing worked. Removed all comments and whitespace, made sure all @import were at the top, etc. I suspect that the Meteor less package is combining them in a way that produces this warning.

**Comment by Azambadar** [comment]
Hi aldeed, does it make any difference if I installed reaction as administrator or not administrator? I originally installed reaction without admin permission and I was getting more errors and then I run as an administrator and now I am getting less errors. 

Thank you for your reply.

**Comment by aldeed** [comment]
@Azambadar I'm not sure we test running on limited accounts. I'd recommend having as many permissions as possible.

**Comment by Azambadar** [comment]
Thank you Aldeed.
