### ISSUE TITLE
cart/submitPayment throwing Exception

### ISSUE THREAD

**Issue by Gouthamve** [reactioncommerce/reaction#464]
I am getting the following exception while trying to call ```cart/submitPayment```.

```javascript
I20150924-01:56:40.566(5.5)? Exception while invoking method 'cart/submitPayment' TypeError: Cannot read property '_id' of undefined
I20150924-01:56:40.566(5.5)?     at [object Object].doValidate (packages/aldeed:collection2/collection2.js:290:1)
I20150924-01:56:40.566(5.5)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:169:1)
I20150924-01:56:40.566(5.5)?     at packages/reactioncommerce:core/server/methods/cart.js:158:1
I20150924-01:56:40.566(5.5)?     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:965:1)
I20150924-01:56:40.567(5.5)?     at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:812:1)
I20150924-01:56:40.568(5.5)?     at [object Object].Meteor.methods.createCart (packages/reactioncommerce:core/server/methods/cart.js:137:1)
I20150924-01:56:40.568(5.5)?     at packages/check/match.js:109:1
I20150924-01:56:40.568(5.5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150924-01:56:40.568(5.5)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
I20150924-01:56:40.568(5.5)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
```

A little digging shows that it stems from here: https://github.com/reactioncommerce/reaction-core/blob/development/server/methods/cart.js#L158-L162

**Comment by Gouthamve** [comment]
Modifying the above method to ```collection.update(selector, modifier)``` like below has gotten into a infinite loop :-1: 

```javascript
ReactionCore.Collections.Accounts.update({
          'userId': staleCartUserId
        }, { 
          $set: {
            state: "expired"
          }
        });
```

part of the log of the infinite loop
```javascript
I20150924-02:52:56.651(5.5)? 21:22:56.650Z  INFO core: Created orderId nABqdATXeqgCCAkqC
I20150924-02:52:56.709(5.5)? 21:22:56.708Z  INFO core: no existing cart. created: RLBd57s6qBAtu4x97 for KHFudoAMLsy9SYkc4
I20150924-02:52:56.744(5.5)? 21:22:56.744Z  INFO core: processed: PjPv7L4T8HqbmapiRfor user: WLgZjogoCwsP9KN4q into RLBd57s6qBAtu4x97
I20150924-02:52:56.746(5.5)? 21:22:56.746Z  INFO core: Transitioned cart gnGbN494XA8q6zLEg to order nABqdATXeqgCCAkqC
I20150924-02:52:56.809(5.5)? 21:22:56.809Z  INFO core: no existing cart. created: TEQLYRnH4hsBgATkC for WLgZjogoCwsP9KN4q
I20150924-02:52:56.840(5.5)? 21:22:56.840Z  INFO core: processed: RLBd57s6qBAtu4x97for user: KHFudoAMLsy9SYkc4 into TEQLYRnH4hsBgATkC
I20150924-02:52:56.994(5.5)? 21:22:56.993Z  INFO core: no existing cart. created: 2bknpwHFAv5zxywrr for KHFudoAMLsy9SYkc4
I20150924-02:52:57.015(5.5)? 21:22:57.015Z  INFO core: processed: TEQLYRnH4hsBgATkCfor user: WLgZjogoCwsP9KN4q into 2bknpwHFAv5zxywrr
I20150924-02:52:57.076(5.5)? 21:22:57.075Z  INFO core: no existing cart. created: JSps45fBFcALiL4fX for WLgZjogoCwsP9KN4q
I20150924-02:52:57.111(5.5)? 21:22:57.110Z  INFO core: processed: 2bknpwHFAv5zxywrrfor user: KHFudoAMLsy9SYkc4 into JSps45fBFcALiL4fX
I20150924-02:52:57.473(5.5)? 21:22:57.473Z  INFO core: no existing cart. created: ysrSWZKKwFxrSBqsT for KHFudoAMLsy9SYkc4
I20150924-02:52:57.503(5.5)? 21:22:57.502Z  INFO core: processed: JSps45fBFcALiL4fXfor user: WLgZjogoCwsP9KN4q into ysrSWZKKwFxrSBqsT
I20150924-02:52:57.598(5.5)? 21:22:57.596Z  INFO core: no existing cart. created: 4WMMhF7cFWfmbPWP9 for WLgZjogoCwsP9KN4q
I20150924-02:52:57.657(5.5)? 21:22:57.657Z  INFO core: processed: ysrSWZKKwFxrSBqsTfor user: KHFudoAMLsy9SYkc4 into 4WMMhF7cFWfmbPWP9
I20150924-02:52:57.684(5.5)? 21:22:57.684Z  INFO core: no existing cart. created: WjAW9xhcJTJ7wAuoa for KHFudoAMLsy9SYkc4
I20150924-02:52:57.714(5.5)? 21:22:57.713Z  INFO core: processed: 4WMMhF7cFWfmbPWP9for user: WLgZjogoCwsP9KN4q into WjAW9xhcJTJ7wAuoa
I20150924-02:52:57.761(5.5)? 21:22:57.760Z  INFO core: no existing cart. created: eft6qHHRJy5niLp3f for WLgZjogoCwsP9KN4q
I20150924-02:52:57.774(5.5)? 21:22:57.774Z  INFO core: processed: WjAW9xhcJTJ7wAuoafor user: KHFudoAMLsy9SYkc4 into eft6qHHRJy5niLp3f
I20150924-02:52:57.790(5.5)? 21:22:57.790Z  INFO core: no existing cart. created: wFRXKco9H8C2sfckT for KHFudoAMLsy9SYkc4
I20150924-02:52:57.821(5.5)? 21:22:57.821Z  INFO core: processed: eft6qHHRJy5niLp3ffor user: WLgZjogoCwsP9KN4q into wFRXKco9H8C2sfckT
I20150924-02:52:57.839(5.5)? 21:22:57.838Z  INFO core: no existing cart. created: T45Wf8nNXrYQirHq2 for WLgZjogoCwsP9KN4q
I20150924-02:52:57.853(5.5)? 21:22:57.853Z  INFO core: processed: wFRXKco9H8C2sfckTfor user: KHFudoAMLsy9SYkc4 into T45Wf8nNXrYQirHq2
```

**Comment by aaronjudd** [comment]
You shouldn't even get there - you have to have a cartId for this method to function. You need to look at why `sessionCart._id` isn't defined - the actual error is being thrown here:

https://github.com/reactioncommerce/reaction-core/blob/development/server/methods/cart.js#L137-L139

**Comment by Gouthamve** [comment]
I can't reproduce this on the latest development branch :+1: :)
