### ISSUE TITLE
Receive server error message when changing currency on client-side

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4662]
## Issue Description
If exchange rates are loaded and you change currency through the drop down receive this error on the server:

Checking that EUR is loaded:

![2018-09-21_15-03-51](https://user-images.githubusercontent.com/72819/45865286-99ad5480-bdaf-11e8-9546-f1492ef36f70.png)

```
07:00:23.956Z ERROR Reaction: The positional operator did not find the match needed from the query.
  MongoError: The positional operator did not find the match needed from the query.
      at Function.MongoError.create (/Users/brenthoover/.meteor/packages/npm-mongo/.3.1.1-rc18.14.h2z5rp.w2z5v++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/error.js:49:10)
      at toError (/Users/brenthoover/.meteor/packages/npm-mongo/.3.1.1-rc18.14.h2z5rp.w2z5v++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/utils.js:149:22)
      at coll.s.topology.update (/Users/brenthoover/.meteor/packages/npm-mongo/.3.1.1-rc18.14.h2z5rp.w2z5v++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb/lib/operations/collection_ops.js:1350:39)
      at /Users/brenthoover/.meteor/packages/npm-mongo/.3.1.1-rc18.14.h2z5rp.w2z5v++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:531:18
      at _combinedTickCallback (internal/process/next_tick.js:131:7)
      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

## Steps to Reproduce
1. Ensure that exchange rates are loaded by checking for `Shops/currencies/EUR/rate`
1. As an anonymous user change currency
1. Observe the server error

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
Reaction: 2.0.0

**Comment by aldeed** [comment]
This UI was removed in final 2.0.0
