### ISSUE TITLE
Server error when submitting IOU payment with no name supplied

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#4678]
## Issue Description
Throws a server error instead of a client-side validation error. No need to wake up a devops admin because somebody forgot to enter a name

```
GraphQL request (1:42)
1: mutation placeOrderWithExampleIOUPayment($input: PlaceOrderWithExampleIOUPaymentInput!) {
                                            ^
2:   placeOrderWithExampleIOUPayment(input: $input) {

    at coercionError (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/utilities/coerceValue.js:179:10)
    at coerceValue (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/utilities/coerceValue.js:53:24)
    at coerceValue (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/utilities/coerceValue.js:132:30)
    at coerceValue (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/utilities/coerceValue.js:55:12)
    at coerceValue (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/utilities/coerceValue.js:132:30)
    at coerceValue (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/utilities/coerceValue.js:55:12)
    at getVariableValues (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/execution/values.js:74:53)
    at buildExecutionContext (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/execution/execute.js:247:63)
    at executeImpl (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/execution/execute.js:140:17)
    at Object.execute (/Users/brenthoover/Projects/js/reaction/node_modules/graphql/execution/execute.js:131:229)
    at doRunQuery (/Users/brenthoover/Projects/js/reaction/node_modules/apollo-server-core/dist/runQuery.js:124:42)
    at /Users/brenthoover/Projects/js/reaction/node_modules/apollo-server-core/dist/runQuery.js:21:56
```

## Steps to Reproduce
1. Place item in cart and checkout
1. Click on Submit Payment for IOU payment form w/o entering a name
1. Observer server-side error

## Possible Solution
Add client-side validation to this form

### Versions
Reaction: 2.0.0-rc1

**Comment by mpaktiti** [comment]
@zenweasel I follow the steps to reproduce, but when I reach the Payment Information I cannot save without entering a name. Should I go ahead and close this?



![image](https://user-images.githubusercontent.com/11715799/60819006-6c4b5f00-a1a7-11e9-9061-11a78bab4193.png)

**Comment by zenweasel** [comment]
Yes. If an issue is quite old like this and pretty simple and you can't reproduce, feel free to just close.
