### ISSUE TITLE
updateVariant throws exception

### ISSUE THREAD

**Issue by vkoudela** [reactioncommerce/reaction#471]
I'm getting this exception on server:
```
I20151002-15:32:36.605(2)? Exception while invoking method 'updateVariant' TypeError: Cannot read property 'inventoryQuantity' of undefined
I20151002-15:32:36.605(2)?     at Object.Cart (common/collections/hooks/hooks.js:258:37)
I20151002-15:32:36.605(2)?     at packages/matb33_collection-hooks/update.js:43:1
I20151002-15:32:36.605(2)?     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
I20151002-15:32:36.605(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20151002-15:32:36.605(2)?     at packages/matb33_collection-hooks/update.js:42:1
I20151002-15:32:36.605(2)?     at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
I20151002-15:32:36.606(2)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20151002-15:32:36.606(2)?     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:41:1)
I20151002-15:32:36.606(2)?     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
I20151002-15:32:36.606(2)?     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:586:1)
```

Steps to reproduce:
1. make fresh RC installation
2. duplicate example product
3. open variants on duplicated product and try to update "Option" field

**Comment by spencern** [comment]
I'm getting this same issue as well when duplicating a product.
Same error on the front end.

Here's the server error that's triggering at the same time:
```
Exception while invoking method 'products/updateVariant' TypeError: Cannot read property 'inventoryQuantity' of undefined   
    at Object.Cart (common/collections/hooks/hooks.js:295:37)                                                               
    at packages/matb33_collection-hooks/update.js:43:1                                                                      
    at Array.forEach (packages/es5-shim/packages/es5-shim.js:458:1)                                                         
    at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)                                         
    at packages/matb33_collection-hooks/update.js:42:1                                                                      
    at Array.forEach (packages/es5-shim/packages/es5-shim.js:458:1)                                                         
    at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)                                         
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:41:1)                           
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)      
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:586:1)                           
```

**Comment by aaronjudd** [comment]
I started with a small refactor of the collection hooks to resolve this issue, but have gone far off that path and have created, and am working on issue https://github.com/reactioncommerce/reaction/issues/510  which will close this issue as well when completed.

**Comment by aaronjudd** [comment]
https://gitter.im/reactioncommerce/reaction?at=565493ec0d143098620f0668 This should be resolved in development branch now.
