### ISSUE TITLE
[bug] Cannot find module '/imports/plugins/core/graphql/server/no-meteor/xforms/id' on startup 

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction#4762]
## Issue Description
Attempting to run startup commands with `docker`, application throws out a console error relating to not being able to find a module on graphql xform id. Cannot start the application.

## Steps to Reproduce
1. Fresh Reaction installation with `docker-compose up` or through `make` with Reaction Platform
2. Notice console output 

**Console Log**: 
```
Error: Cannot find module '/imports/plugins/core/graphql/server/no-meteor/xforms/id'
    at makeMissingError (packages/modules-runtime.js:231:12)
    at require (packages/modules-runtime.js:241:19)
    at page.js (imports/plugins/custom/contentful/server/no-meteor/xforms/page.js:1:191)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/contentful/server/no-meteor/resolvers/Page/index.js:1:105)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at index.js (imports/plugins/custom/contentful/server/no-meteor/resolvers/index.js:1:23)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at register.js (imports/plugins/custom/contentful/register.js:1:322)
    at fileEvaluate (packages/modules-runtime.js:339:7)
    at require (packages/modules-runtime.js:238:16)
    at plugins.js (server/plugins.js:1:5332)
    at fileEvaluate (packages/modules-runtime.js:339:7)
=> Exited with code: 1

16:13:17.958Z  WARN Reaction: No shop matching domain 'null'. Defaulting to Primary Shop.
16:13:18.875Z  WARN Reaction: No shop matching domain 'null'. Defaulting to Primary Shop.
16:13:19.002Z  WARN Reaction: No shop matching domain 'null'. Defaulting to Primary Shop.
16:13:19.004Z  WARN Reaction: No shop matching domain 'null'. Defaulting to Primary Shop.
16:13:19.007Z  WARN Reaction: No shop matching domain 'null'. Defaulting to Primary Shop.
```

### Versions
Reaction : Release 1.17 (https://github.com/reactioncommerce/reaction/pull/4761)

**Comment by aldeed** [comment]
@jeffcorpuz Based on the stack trace, I see that this error comes from the custom `contentful` plugin, which I believe is only compatible with 2.0.0+. If you remove that plugin the app should start up.

**Comment by jeffcorpuz** [comment]
@aldeed you are correct. 
@dancastellon clarified it is only for 2.x+ line, will not be ported to 1.xx release.
