### ISSUE TITLE
Exception on Server Console

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#484]
Noticed this on Server Console.  Not sure what caused it. However when it occurred  Reaction was not responsive at all in Browser.  Could be a one off or boundary condition but message is indicating problem.

Exception from sub ServiceConfiguration id abdShNjZ2AuvvvQTD MinimongoError: You cannot currently mix including and excluding fields.
    at MinimongoError (packages/minimongo/minimongo.js:44:1)
    at packages/minimongo/projection.js:80:1
    at Array.forEach (packages/es5-shim/packages/es5-shim.js:458:1)
    at Function._.each._.forEach (packages/underscore/packages/underscore.js:134:1)
    at projectionDetails (packages/minimongo/projection.js:74:1)
    at Function.LocalCollection._compileProjection (packages/minimongo/projection.js:12:1)
    at new OplogObserveDriver (packages/mongo/oplog_observe_driver.js:92:1)
    at [object Object].MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1221:1)
    at [object Object].Cursor.observeChanges (packages/mongo/mongo_driver.js:911:1)
    at Function.Mongo.Collection._publishCursor (packages/mongo/collection.js:308:1)

**Comment by aaronjudd** [comment]
That's a new one I haven't seen.  `ServiceConfiguration` is a core Meteor method, more research needed..

**Comment by mikemurray** [comment]
It's probably because of this publication in reaction-accounts. I need to test to be sure.

```
  return ServiceConfiguration.configurations.find({}, {
    fields: {
      secret: 0,
      enabled: 1
    }
  });
```
