### ISSUE TITLE
[Bug] Paypal payment error 

### ISSUE THREAD

**Issue by lhz516** [reactioncommerce/reaction#491]
I got this error message after Paypal button checkout. 
-------------------------------------------------------------------------------------------
Exception while invoking method 'cart/submitPayment' Error: Match error: Amount must be a number
    at [object Object].SimpleSchema.condition (packages/aldeed_simple-schema/packages/aldeed_simple-schema.js:1465:1)
    at checkSubtree (packages/check/match.js:220:1)
    at check (packages/check/match.js:32:1)
    at [object Object].Meteor.methods.cart/submitPayment (server/methods/cart.js:547:5)
    at [object Object].ReactionCore.MethodHooks._wrappers.(anonymous function) (server/methods/hooks/hooks.js:103:21)
    at packages/check/match.js:109:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:108:1)
    at maybeAuditArgumentChecks (livedata_server.js:1689:18)
    at livedata_server.js:708:19
Sanitized and reported to the client as: Amount must be a number [400]

**Comment by vhmh2005** [comment]
I still got this error after upgrading reaction-paypal to the latest code on development branch

![image](https://cloud.githubusercontent.com/assets/877578/10754429/1a2f213a-7cca-11e5-826d-bce28f77435c.png)

**Comment by aaronjudd** [comment]
@vhmh2005 I'll take another look.  Can you paste the output of `meteor list` here as well, I'd like to see the versions you're using.

**Comment by aaronjudd** [comment]
published v1.2.3 that has a fix for this, as well as in the development branch.
