### ISSUE TITLE
Getting Error while creating Variant

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#492]
Exception on Clone Variant. That might have been fixed in recent build. Want to make sure it is recorded.  

 Exception while invoking method 'products/cloneVariant' TypeError: Cannot call method 'push' of undefined
     at server/methods/products.js:41:19
     at [object Object].Meteor.methods.products/cloneVariant (server/methods/products.js:45:6)
     at packages/check/packages/check.js:117:1
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/packages/check.js:116:1)
     at maybeAuditArgumentChecks (livedata_server.js:1689:18)
     at livedata_server.js:708:19
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at livedata_server.js:706:40
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
https://guides.github.com/features/mastering-markdown/

**Comment by aaronjudd** [comment]
This might be a duplicate of https://github.com/reactioncommerce/reaction/issues/490, I'll check it out though. Pull `development` branch in case this solves it for you.

**Comment by hrath2015** [comment]
Tested on Latest Pull. Working OK both Product and Variant.
--Thanks
