### ISSUE TITLE
[bug] Exception while invoking method 'cart/setShipmentAddress' during checkout

### ISSUE THREAD

**Issue by jeffcorpuz** [reactioncommerce/reaction#4928]
## Issue Description
Upon selecting an address (existing or newly created) during the checkout process causes an Exception error in the console,  blocking the process as a result.

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. Go through regular checkout process
2. Select/create an address to go through "Shipping" Step 
3. Verify console error & blank shipping section.

## Screenshot(s)
<img width="1439" alt="screen shot 2019-01-19 at 8 12 53 am" src="https://user-images.githubusercontent.com/6117033/51413166-0bf93e80-1bc2-11e9-954e-d0b622797612.png">

## Logs
```
Exception while invoking method 'cart/setShipmentAddress' TypeError: undefined is not iterable
    at catalogProducts.reduce (imports/plugins/included/shipping-rates/server/no-meteor/util/helpers.js:94:10)
    at Array.reduce (<anonymous>)
    at Promise.asyncApply (imports/plugins/included/shipping-rates/server/no-meteor/util/helpers.js:93:34)
    at /home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (imports/plugins/included/shipping-rates/server/no-meteor/util/getShippingRestrictionAttributes.js:25:24)
    at /home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (imports/plugins/included/shipping-rates/server/no-meteor/getFulfillmentMethodsWithQuotes.js:89:22)
    at /home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (imports/plugins/core/shipping/server/no-meteor/queries/getFulfillmentMethodsWithQuotes.js:22:3)
    at /home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
    at Promise.asyncApply (imports/plugins/core/shipping/server/no-meteor/mutations/updateFulfillmentOptionsForGroup.js:89:14)
    at /home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
 => awaited here:
    at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
    at MethodInvocation.setShipmentAddress (imports/plugins/core/cart/server/methods/setShipmentAddress.js:48:9)
    at currentArgumentChecker.withValue (packages/check/match.js:118:15)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Object._failIfArgumentsAreNotAllChecked (packages/check/match.js:116:43)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1764:18)
    at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at Promise (packages/ddp-server/livedata_server.js:715:46)
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
21:07:14.879Z ERROR Reaction:  (errorId=cjr2jbrjz00076kllmi7so72s)
  path: [
    "updateFulfillmentOptionsForGroup"
  ]
21:07:16.873Z ERROR Reaction:  (errorId=cjr2jbt3d00086kllin86mght)
  path: [
    "updateFulfillmentOptionsForGroup"
  ]
```

### Versions
Reaction : release-2.0.0.rc.9 (#4922)

**Comment by MadhuRakshith15** [comment]
Any update on this issue?

**Comment by jeffcorpuz** [comment]
Hi @MadhuRakshith15 it is being looked at the moment.

**Comment by addzep** [comment]
I am also having this issue consistently. 

Steps to Reproduce:
1. Select a new added product or select any previous product.
2. Checkout using guest or registered user.
3. Add Address, and then error.

**reaction -v**
Node: 10.15.0
NPM: 6.4.1
Meteor Node: 8.11.4
Meteor NPM: 6.4.1
Reaction CLI: 0.29.0
