### ISSUE TITLE
Error when retrieving Shipment methods

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5013]
## Issue Description
When attempting to check out the user does not receive any shipment method options and cannot check out.

You receive this error in the server console

```
07:59:02.024Z ERROR Reaction:
  Error in "afterCartUpdate" consumer TypeError: undefined is not iterable
      at catalogProducts.reduce (imports/plugins/core/shipping/server/no-meteor/util/helpers.js:85:5)
      at Array.reduce (<anonymous>)
      at Promise.asyncApply (imports/plugins/core/shipping/server/no-meteor/util/helpers.js:84:18)
      at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/plugins/core/shipping/server/no-meteor/util/extendCommonOrder.js:21:24)
      at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/plugins/included/surcharges/server/no-meteor/getSurcharges.js:15:28)
      at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/plugins/included/surcharges/server/no-meteor/startup.js:33:30)
      at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
   => awaited here:
      at Function.Promise.await (/app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
      at Promise.asyncApply (imports/node-app/core/util/appEvents.js:24:5)
      at /app/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40```
```

Note that this is not reproducible with the test data. Will provide reproduction environment privately

## Steps to Reproduce
1. Add an item to cart
1. Proceed to checkout
1. Observe that you receive no shipping methods and cannot checkout

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

### Versions
RC9

**Comment by aldeed** [comment]
@zenweasel This is seemingly because some products have no tags, so `product.tagIds` isn't an array in the catalog item. It's a code bug, but it could be fixed by ensuring that `tagIds` is an empty array, or you could run this to fix now:

```js
Catalog.updateMany({ "product.tagIds": null }, { $set: { "product.tagIds": [] });
```

**Comment by kieckhafer** [comment]
@aldeed makes sense. 

However, at least in our Operator UI, tags are required on a `Product` (not necessarily a `CatalogProduct`). You can't save a `Product` to the `Products` collection without tags on it. Should we make tagIds required in the `Catalog` then too?

**Comment by zenweasel** [comment]
@kieckhafer Is it required in the schema? I would expect that almost no enterprise users will be using our Product Admin UI.

**Comment by kieckhafer** [comment]
@zenweasel after looking into it, it seems
like the UI requires it, not the schema itself. So when we move the UI into the admin operator, we’ll remove that requirement

**Comment by zenweasel** [comment]
@aldeed Should we enforce the tags through the schema?

**Comment by aldeed** [comment]
No the schemas are correct IMO. You should not be required to have any tags on products or catalog products. The only issue was with places in the code where we were assuming there would always be tags, which was an incorrect assumption.
