### ISSUE TITLE
Error shows up in Order Details admin panel.

### ISSUE THREAD

**Issue by cooloney** [reactioncommerce/reaction#506]
```
Exception in delivering result of invoking 'stripeCapture': TypeError: Cannot read property 'saved' of undefined
    at server/methods/orders.js:494:23
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
    at packages/meteor/dynamics_nodejs.js:123:1
    at [object Object]._.extend.apply (livedata_server.js:1627:7)
    at [object Object]._.extend.call (livedata_server.js:1553:17)
    at Object.Meteor.Stripe.capture (lib/stripe.js:19:12)
    at server/methods/orders.js:490:41
    at Array.forEach (packages/es5-shim/.npm/package/node_modules/es5-shim/es5-shim.js:417:1)
    at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
    at [object Object].Meteor.methods.orders/capturePayments (server/methods/orders.js:484:7)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at packages/check/match.js:103:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:102:1)
    at maybeAuditArgumentChecks (livedata_server.js:1695:18)
    at livedata_server.js:708:19
```

**Comment by mikemurray** [comment]
You might need to pull the latest development branch of reaction-stripe as well

**Comment by zenweasel** [comment]
@cooloney I am able to enter and process an order via Stripe.Is there something specific I need to do to replicate this error?

**Comment by cooloney** [comment]
Oh, I think it's probably fixed with the latest branch. I haven't seen that again after I pull in the latest branch. Let me close it.
