### ISSUE TITLE
Error on server: `TypeError: moment is not a function`

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#5083]
## Issue Description
Receive the following error after server runs for some time
```
Exception in setTimeout callback: TypeError: moment is not a function
    at JobQueue.Jobs.processJobs [as worker] (imports/plugins/included/jobcontrol/server/jobs/cleanup.js:45:23)
    at JobQueue._process (/app/programs/server/npm/node_modules/@reactioncommerce/job-queue/dist/common/jobFactory.js:432:23)
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
    at packages/meteor.js:620:25
    at runWithEnvironment (packages/meteor.js:1356:24)
```

## Steps to Reproduce
1. Start server
1. Wait until the `cleanup` jobs runs
1. Observe error

## Possible Solution
`moment` is being lazyloaded in a server function. We shouldn't do that 

### Versions
RC11

**Comment by aldeed** [comment]
Pretty sure this went away after the job-queue rewrite
