### ISSUE TITLE
Platform Install Error on Reaction Container

### ISSUE THREAD

**Issue by richardkeller411** [reactioncommerce/reaction#5167]
On Mac fresh install.   

I get this error when trying to run
 Error: Command failed: REACTION_METEOR_APP_COMMAND_START_TIME=1557078186799 meteor run --no-lint --no-release-check --raw-logs
    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at run (file:///opt/reaction/src/.reaction/run/index.mjs:41:18)
    at file:///opt/reaction/src/.reaction/run/index.mjs:49:1
    at ModuleJob.run (internal/loader/ModuleJob.js:97:14)
    at <anonymous>
  error: null,
  cmd: 'REACTION_METEOR_APP_COMMAND_START_TIME=1557078186799 meteor run --no-lint --no-release-check --raw-logs ',
  file: '/bin/sh',
  args:
   [ '/bin/sh',
     '-c',
     'REACTION_METEOR_APP_COMMAND_START_TIME=1557078186799 meteor run --no-lint --no-release-check --raw-logs ' ],
  options:
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     file: '/bin/sh',
     args:
      [ '/bin/sh',
        '-c',
        'REACTION_METEOR_APP_COMMAND_START_TIME=1557078186799 meteor run --no-lint --no-release-check --raw-logs ' ],
     envPairs:
      [ 'TOOL_NODE_FLAGS=',
        'NODE_VERSION=8.11.4',
        'HOSTNAME=6562ae95b82a',
        'METEOR_WATCH_POLLING_INTERVAL_MS=10000',
        'METEOR_VERSION=1.8.0.2',
        'METEOR_DISABLE_OPTIMISTIC_CACHING=1',
        'REACTION_EMAIL=admin@localhost',
        'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor:/opt/reaction/src/node_modules/.bin',
        'PWD=/opt/reaction/src',
        'MONGO_URL=mongodb://mongo:27017/reaction',
        'REACTION_USER=Admin',
        'APP_BUNDLE_DIR=/opt/reaction/dist',
        'ROOT_URL=http://localhost:3000',
        'HYDRA_TOKEN_URL=http://hydra:4444/oauth2/token',
        'SHLVL=1',
        'HOME=/home/node',
        'REACTION_AUTH=r3@cti0n',
        'YARN_VERSION=1.6.0',
        'OAUTH2_CLIENT_DOMAINS=http://localhost:4000',
        'REACTION_DOCKER_BUILD=true',
        'REACTION_USER_NAME=admin',
        'REACTION_SECURE_DEFAULT_ADMIN=false',
        'APP_SOURCE_DIR=/opt/reaction/src',
        'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
        'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
        'HYDRA_ADMIN_URL=http://hydra:4445',
        'IDENTITY_PROVIDER_MODE=all',
        '_=/usr/local/bin/node' ],
     killSignal: undefined },
  envPairs:
   [ 'TOOL_NODE_FLAGS=',
     'NODE_VERSION=8.11.4',
     'HOSTNAME=6562ae95b82a',
     'METEOR_WATCH_POLLING_INTERVAL_MS=10000',
     'METEOR_VERSION=1.8.0.2',
     'METEOR_DISABLE_OPTIMISTIC_CACHING=1',
     'REACTION_EMAIL=admin@localhost',
     'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/node/.meteor:/home/node/.meteor:/opt/reaction/src/node_modules/.bin',
     'PWD=/opt/reaction/src',
     'MONGO_URL=mongodb://mongo:27017/reaction',
     'REACTION_USER=Admin',
     'APP_BUNDLE_DIR=/opt/reaction/dist',
     'ROOT_URL=http://localhost:3000',
     'HYDRA_TOKEN_URL=http://hydra:4444/oauth2/token',
     'SHLVL=1',
     'HOME=/home/node',
     'REACTION_AUTH=r3@cti0n',
     'YARN_VERSION=1.6.0',
     'OAUTH2_CLIENT_DOMAINS=http://localhost:4000',
     'REACTION_DOCKER_BUILD=true',
     'REACTION_USER_NAME=admin',
     'REACTION_SECURE_DEFAULT_ADMIN=false',
     'APP_SOURCE_DIR=/opt/reaction/src',
     'HYDRA_OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect',
     'MONGO_OPLOG_URL=mongodb://mongo:27017/local',
     'HYDRA_ADMIN_URL=http://hydra:4445',
     'IDENTITY_PROVIDER_MODE=all',
     '_=/usr/local/bin/node' ],
  stderr: null,
  stdout: null,
  pid: 58,
  output: [ null, null, null ],
  signal: null,
  status: 137 }

Error: App failed to start

**Comment by richardkeller411** [comment]
I allocate a lot more.  Got it working on windows.  Abandoned Mac for a second.
