### ISSUE TITLE
Reaction Next Starter Not Loading

### ISSUE THREAD

**Issue by moeghashim** [reactioncommerce/reaction#5214]
## Issue Description
Upon completing the installation and running 
```
cd reaction-next-starterkit
docker-compose logs -f
```

I get the following error
```
web_1  | [9:41:23 AM] Compiling server
web_1  | [9:41:23 AM] Compiled server in 126ms
web_1  | [9:41:23 AM] Compiling client
web_1  | [9:41:24 AM] Compiled client in 685ms
web_1  |  DONE  Compiled successfully in 827ms9:41:24 AM
web_1  | 
web_1  | > Building page: /productGrid
web_1  |  WAIT  Compiling...9:41:53 AM
web_1  | 
web_1  | [9:41:53 AM] Compiling server
web_1  | [9:41:53 AM] Compiling client
web_1  | [9:41:54 AM] Compiled client in 1s
web_1  |  DONE  Compiled successfully in 1423ms9:41:54 AM
web_1  | 
web_1  | [9:41:55 AM] Compiled server in 2s
web_1  | Unable to access the GraphQL API. Is it running and accessible at http://reaction.api.reaction.localhost:3000/graphql-alpha from the Storefront UI server?
web_1  | { Error: Network error: request to http://reaction.api.reaction.localhost:3000/graphql-alpha failed, reason: getaddrinfo ENOTFOUND reaction.api.reaction.localhost reaction.api.reaction.localhost:3000
web_1  |     at new ApolloError (/usr/local/src/node_modules/apollo-client/bundle.umd.js:99:32)
web_1  |     at /usr/local/src/node_modules/apollo-client/bundle.umd.js:967:45
web_1  |     at /usr/local/src/node_modules/apollo-client/bundle.umd.js:1329:21
web_1  |     at Array.forEach (<anonymous>)
web_1  |     at /usr/local/src/node_modules/apollo-client/bundle.umd.js:1328:22
web_1  |     at Map.forEach (<anonymous>)
web_1  |     at QueryManager.broadcastQueries (/usr/local/src/node_modules/apollo-client/bundle.umd.js:1323:26)
web_1  |     at /usr/local/src/node_modules/apollo-client/bundle.umd.js:917:35
web_1  |     at process._tickCallback (internal/process/next_tick.js:68:7)
web_1  |   graphQLErrors: [],
web_1  |   networkError:
web_1  |    { FetchError: request to http://reaction.api.reaction.localhost:3000/graphql-alpha failed, reason: getaddrinfo ENOTFOUND reaction.api.reaction.localhost reaction.api.reaction.localhost:3000
web_1  |        at ClientRequest.<anonymous> (/usr/local/src/node_modules/node-fetch/index.js:133:11)
web_1  |        at ClientRequest.emit (events.js:198:13)
web_1  |        at Socket.socketErrorListener (_http_client.js:392:9)
web_1  |        at Socket.emit (events.js:198:13)
web_1  |        at emitErrorNT (internal/streams/destroy.js:91:8)
web_1  |        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
web_1  |        at process._tickCallback (internal/process/next_tick.js:63:19)
web_1  |      name: 'FetchError',
web_1  |      message:
web_1  |       'request to http://reaction.api.reaction.localhost:3000/graphql-alpha failed, reason: getaddrinfo ENOTFOUND reaction.api.reaction.localhost reaction.api.reaction.localhost:3000',
web_1  |      type: 'system',
web_1  |      errno: 'ENOTFOUND',
web_1  |      code: 'ENOTFOUND' },
web_1  |   message:
web_1  |    'Network error: request to http://reaction.api.reaction.localhost:3000/graphql-alpha failed, reason: getaddrinfo ENOTFOUND reaction.api.reaction.localhost reaction.api.reaction.localhost:3000',
web_1  |   extraInfo: undefined }
```
### Versions
v2.0.0-rc.11

**Comment by zenweasel** [comment]
@moeghashim It just looks like the API server is not running. It needs to be running in order for the frontend to work.

**Comment by moeghashim** [comment]
@zenweasel when I run `make start` all services start here is a screenshot https://www.dropbox.com/s/xeyln1fxh4zfl0g/Screenshot%202019-06-18%2010.56.35.png?dl=0. But i still can't load Reaction.
I noticed others are facing the same issue https://github.com/reactioncommerce/reaction-platform/issues/50

Can you advise how to make sure the API server is running?

**Comment by nnnnat** [comment]
@moeghashim once you start the platform can you view the logs of the Reaction container and see if there is an error or if the service is just slow to start (it can take a long time for first start up on macOS).
From the root directory of the platform `cd reaction` then check the container logs `docker-compose logs -f reaction` (ctl+c to exit). My guess is either the reaction service is crashing or taking an incredibly long time to start.

**Comment by moeghashim** [comment]
I restarted docker containers and everything worked just fine.
Thanks!
