### ISSUE TITLE
Error while inviting Members. 

### ISSUE THREAD

**Issue by hrath2015** [reactioncommerce/reaction#525]
Getting error as below when inviting members. 

Exception while invoking method 'accounts/inviteShopMember' ReferenceError: SSR is not defined
    at [object Object].Meteor.methods.accounts/inviteShopMember (server/methods/accounts.js:271:9)
    at packages/check/packages/check.js:117:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/packages/check.js:116:1)
    at maybeAuditArgumentChecks (livedata_server.js:1689:18)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46

**Comment by hrath2015** [comment]
Re installed everything from Scratch. Error gone after that.
