### ISSUE TITLE
TempFileStoreWorker: TempFileStore does not contain file 

### ISSUE THREAD

**Issue by karbal** [reactioncommerce/reaction#5512]
```
TempFileStoreWorker: TempFileStore does not contain file d5e0311d871345167975a9119921d786 referenced by "Media" record with ID 5d2755c61515e80241e35667. Clearing tempStoreId from the FileRecord.
reaction_1  | Error: FileCollection update requires a single ID and updated document. Multiple not supported. Received: 5d2755c61515e80241e35667
reaction_1  |     at MeteorFileCollection._callee2$ (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/common/FileCollection.js:136:75)
reaction_1  |     at tryCatch (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:62:40)
reaction_1  |     at Generator.invoke [as _invoke] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:296:22)
reaction_1  |     at Generator.prototype.(anonymous function) [as next] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:114:21)
reaction_1  |     at step (/opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
reaction_1  |     at /opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
reaction_1  |     at new Promise (<anonymous>)
reaction_1  |     at new F (/opt/reaction/src/node_modules/core-js/library/modules/_export.js:36:28)
reaction_1  |     at MeteorFileCollection.<anonymous> (/opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
reaction_1  |     at MeteorFileCollection.update (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/common/FileCollection.js:139:185)
reaction_1  |     at TempFileStoreWorker._callee2$ (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/node/TempFileStoreWorker.js:74:30)
reaction_1  |     at tryCatch (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:62:40)
reaction_1  |     at Generator.invoke [as _invoke] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:296:22)
reaction_1  |     at Generator.prototype.(anonymous function) [as next] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:114:21)
reaction_1  |     at step (/opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
reaction_1  |     at /opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
reaction_1  | TempFileStoreWorker: TempFileStore does not contain file d5e0311d871345167975a9119921d786 referenced by "Media" record with ID 5d2755c71515e80241e3566a. Clearing tempStoreId from the FileRecord.
reaction_1  | Error: FileCollection update requires a single ID and updated document. Multiple not supported. Received: 5d2755c71515e80241e3566a
reaction_1  |     at MeteorFileCollection._callee2$ (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/common/FileCollection.js:136:75)
reaction_1  |     at tryCatch (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:62:40)
reaction_1  |     at Generator.invoke [as _invoke] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:296:22)
reaction_1  |     at Generator.prototype.(anonymous function) [as next] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:114:21)
reaction_1  |     at step (/opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
reaction_1  |     at /opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
reaction_1  |     at new Promise (<anonymous>)
reaction_1  |     at new F (/opt/reaction/src/node_modules/core-js/library/modules/_export.js:36:28)
reaction_1  |     at MeteorFileCollection.<anonymous> (/opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
reaction_1  |     at MeteorFileCollection.update (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/common/FileCollection.js:139:185)
reaction_1  |     at TempFileStoreWorker._callee2$ (/opt/reaction/src/node_modules/@reactioncommerce/file-collections/dist/node/TempFileStoreWorker.js:74:30)
reaction_1  |     at tryCatch (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:62:40)
reaction_1  |     at Generator.invoke [as _invoke] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:296:22)
reaction_1  |     at Generator.prototype.(anonymous function) [as next] (/opt/reaction/src/node_modules/regenerator-runtime/runtime.js:114:21)
reaction_1  |     at step (/opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
reaction_1  |     at /opt/reaction/src/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

**Comment by aldeed** [comment]
@karbal Without more context and reproduction steps, there isn't much anyone can do to help.
