### ISSUE TITLE
[v2.6.0 ]address.addressName is not allowed by the schema

### ISSUE THREAD

**Issue by yashutanna** [reactioncommerce/reaction#5741]
## Prerequisites
* [ ] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
when using the graphql API to add an address, we are unable to provide an address name.

**Error:**
```{
  "errors": [
    {
      "message": "address.addressName is not allowed by the schema",
      "locations": [
        {
          "line": 78,
          "column": 3
        }
      ],
      "path": [
        "setShippingAddressOnCart"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT",
        "exception": {
          "eventData": {},
          "error": "validation-error",
          "isClientSafe": true,
          "reason": "address.addressName is not allowed by the schema",
          "details": [
            {
              "name": "address.addressName",
              "type": "keyNotInSchema",
              "value": "Home",
              "message": "address.addressName is not allowed by the schema"
            }
          ],
          "stacktrace": [
            "ReactionError: address.addressName is not allowed by the schema",
            "    at Function.SimpleSchema.defineValidationErrorTransform.error [as validationErrorTransform] (imports/collections/schemas/schemaErrors.js:8:20)",
            "    at /opt/reaction/src/node_modules/simpl-schema/dist/SimpleSchema.js:757:30",
            "    at Array.forEach (<anonymous>)",
            "    at SimpleSchema.validate (/opt/reaction/src/node_modules/simpl-schema/dist/SimpleSchema.js:730:15)",
            "    at Promise.asyncApply (imports/plugins/core/cart/server/no-meteor/mutations/setShippingAddressOnCart.js:29:3)",
            "    at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40",
            " => awaited here:",
            "    at Function.Promise.await (/home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)",
            "    at Promise.asyncApply (imports/plugins/core/cart/server/no-meteor/resolvers/Mutation/setShippingAddressOnCart.js:25:9)",
            "    at /home/node/.meteor/packages/promise/.0.11.2.1gwulfb.vjny++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40"
          ]
        }
      }
    }
  ],
  "data": null
}```

## Steps to Reproduce
Please provide starting context, i.e. logged in as a user, configure a particular payment method.
1. add an address to a cart using the `setShippingAddressOnCart` mutation

## Possible Solution
Update schema to allow for user to input address name as an alias

### Versions
reaction 2.6.0

**Comment by manueldelreal** [comment]
@yashutanna do you still have this issue on the latest version?

**Comment by willopez** [comment]
resolved in https://github.com/reactioncommerce/reaction/pull/6076
