### ISSUE TITLE
Use fallback global templates for emailing when there is no associated shop

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/reaction#5797]
We have a catch-22 with these having the MAIL_URL ENV.

If you start the API fresh, you have to create a new account before you make a shop.

If the email config is set in ENV, then a welcome email will be sent for that new account, but that requires the shop to be created as it uses some values for the email template.

If I do some browser refreshing I can get the setup process to continue in the admin and set up the shop. With the shop set up, if I try to make a customer account and get the second error.

(first account)

```
api_1    | 23:56:13.823Z ERROR Reaction: Error sending welcome email but account was created
api_1    |   TypeError: Cannot read property 'name' of null
api_1    |       at sendWelcomeEmail (file:///usr/local/src/app/src/core-services/account/util/sendWelcomeEmail.js:58:20)
api_1    |       at runMicrotasks (<anonymous>)
api_1    |       at processTicksAndRejections (internal/process/task_queues.js:93:5)
api_1    |       at async Object.createAccount (file:///usr/local/src/app/src/core-services/account/mutations/createAccount.js:94:5)
api_1    |       at async buildContext (file:///usr/local/src/app/src/core/util/buildContext.js:59:19)
api_1    |       at async ApolloServer.context (file:///usr/local/src/app/src/core/createApolloServer.js:60:7)
```

(second account)

```
api_1    | 00:28:42.600Z ERROR Reaction: Error sending welcome email but account was created
api_1    |   TypeError: Cannot read property 'language' of null
api_1    |       at sendWelcomeEmail (file:///usr/local/src/app/src/core-services/account/util/sendWelcomeEmail.js:80:74)
api_1    |       at runMicrotasks (<anonymous>)
api_1    |       at processTicksAndRejections (internal/process/task_queues.js:93:5)
api_1    |       at async Object.createAccount (file:///usr/local/src/app/src/core-services/account/mutations/createAccount.js:94:5)
api_1    |       at async buildContext (file:///usr/local/src/app/src/core/util/buildContext.js:59:19)
```

**Comment by aldeed** [comment]
@mikemurray I think I resolved these errors in my PR that was merged right after you wrote this.

**Comment by aldeed** [comment]
Note that although this is fixed by not sending an email when we don't yet have any shop, the best fix would be to have a non-shop-specific set of fallback templates. This issue can remain open to track that.
