### ISSUE TITLE
Remove cart item is causing the error

### ISSUE THREAD

**Issue by newsiberian** [reactioncommerce/reaction#611]
Hello,
![error1](https://cloud.githubusercontent.com/assets/11130487/11933609/a59045c2-a81e-11e5-8ab9-97bd6a95c99e.png)

This happens because `inventory/clearStatus` method running twice: on client (where throws this error) and on server where forks fine. So, why we have this method in `common` folder?

Also, where is two more methods in this file which calls `ReactionInventory.Log` object, which is undefined from client side...

**Comment by aaronjudd** [comment]
It doesn't have to be in common, other than performance wise, the user will see an immediate action, where's the remove server side could be slower because of the hooks.  We could just use a stub if this becomes an issue though.

**Comment by aaronjudd** [comment]
Fix needed for broken tests.


```
I20151230-08:36:16.076(-8)? jasmine-server-integration: 78 tests passed (6s)
W20151230-08:36:16.076(-8)? (STDERR) jasmine-server-integration: 1 tests failed
W20151230-08:36:16.076(-8)? (STDERR) cart methods cart items cart/removeFromCart should remove item from cart
W20151230-08:36:16.076(-8)? (STDERR) Error: Match error: Failed Match.OneOf or Match.Optional validation
W20151230-08:36:16.076(-8)? (STDERR) meteor://💻app/packages/check/match.js:33:1: Error: Match error: Failed Match.OneOf or Match.Optional validation
W20151230-08:36:16.076(-8)? (STDERR)   at check (meteor://💻app/packages/check/match.js:33:1)
W20151230-08:36:16.076(-8)? (STDERR)   at [object Object].Meteor.methods.cart/removeFromCart (meteor://💻app/server/methods/cart.js:259:5)
W20151230-08:36:16.077(-8)? (STDERR)   at maybeAuditArgumentChecks (meteor://💻app/livedata_server.js:1698:12)
W20151230-08:36:16.077(-8)? (STDERR)   at meteor://💻app/livedata_server.js:1611:18
W20151230-08:36:16.077(-8)? (STDERR)   at [object Object]._.extend.withValue (meteor://💻app/packages/meteor/dynamics_nodejs.js:56:1)
W20151230-08:36:16.077(-8)? (STDERR)   at [object Object]._.extend.apply (meteor://💻app/livedata_server.js:1610:45)
W20151230-08:36:16.077(-8)? (STDERR)   at [object Object]._.extend.call (meteor://💻app/livedata_server.js:1553:17)
W20151230-08:36:16.077(-8)? (STDERR)   at meteor://💻app/tests/jasmine/server/integration/cart.js:87:18
```

**Comment by aaronjudd** [comment]
Resolved by https://github.com/reactioncommerce/reaction/pull/631
