### ISSUE TITLE
Variants with images cannot be duplicated / cloned

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction#6310]
When attempting to duplicate a variant, if there is an image attached to the original variant, the following error happens, and the reaction container shuts down:

````
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (undefined)
at FileRecord.emit (events.js:304:17)
at FileRecord.EventEmitter.emit (domain.js:486:12)
at GridWriteStream.emitError (/usr/local/src/app/node_modules/@reactioncommerce/file-collections-sa-base/dist/StorageAdapter.js:162:18)
at GridWriteStream.emit (events.js:327:22)
at GridWriteStream.EventEmitter.emit (domain.js:486:12)
at GridWriteStream.FlushWritable.emit (/usr/local/src/app/node_modules/flushwritable/lib/FlushWritable.js:37:31)
at GridWriteStream._error (/usr/local/src/app/node_modules/gridfs-stream/lib/writestream.js:246:7)
at /usr/local/src/app/node_modules/gridfs-stream/lib/writestream.js:265:8
at processTicksAndRejections (internal/process/task_queues.js:75:11) {
code: 'ERR_UNHANDLED_ERROR',
context: undefined
}
20:01:12.444Z INFO Reaction: Stopping Reaction API...
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (undefined)
at FileRecord.emit (events.js:304:17)
at FileRecord.EventEmitter.emit (domain.js:486:12)
at GridWriteStream.emitError (/usr/local/src/app/node_modules/@reactioncommerce/file-collections-sa-base/dist/StorageAdapter.js:162:18)
at GridWriteStream.emit (events.js:327:22)
at GridWriteStream.EventEmitter.emit (domain.js:486:12)
at GridWriteStream.FlushWritable.emit (/usr/local/src/app/node_modules/flushwritable/lib/FlushWritable.js:37:31)
at GridWriteStream._error (/usr/local/src/app/node_modules/gridfs-stream/lib/writestream.js:246:7)
at /usr/local/src/app/node_modules/gridfs-stream/lib/writestream.js:265:8
at processTicksAndRejections (internal/process/task_queues.js:75:11) {
code: 'ERR_UNHANDLED_ERROR',
context: undefined
}
[nodemon] app crashed - waiting for file changes before starting...
```

Steps to recreate:
1. Create a product with a variant, and add an image to the variant
1. Attempt to duplicate / clone variant 
1. See above error

**Comment by focusaurus** [comment]
OK great. I can confirm it's the same situation in that something is calling `stream.destroy()` and we are probably propagating the empty error again. The fix will exactly mirror the fix for #6298 but best to handle these separately as these are a slow chore to get fixed with numerous new packages to publish and test, etc.

**Comment by focusaurus** [comment]
I think the place to fix this is [here in StorageAdapter.js](https://github.com/reactioncommerce/reaction-file-collections/blob/9e2551d3e8ca887a54e6e735df3533b70481d532/packages/file-collections-sa-base/src/StorageAdapter.js#L159). Check for missing error and disregard instead of propagating.

**Comment by focusaurus** [comment]
OK reproduced locally and verified a fix. Will go another round through the dep tree.
