### ISSUE TITLE
Cloning and running Reaction gives you an error that prevents it from starting

### ISSUE THREAD

**Issue by brent-hoover** [reactioncommerce/reaction#6388]
## Issue Description
Trying to develop by running the project gives an error.

```
»» npm run start
> node --experimental-modules --experimental-json-modules ./src/index.js

(node:101093) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
08:55:33.097Z ERROR Reaction:
  The requested module '@accounts/mongo' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
  For example:
  import pkg from '@accounts/mongo';
  const { Mongo } = pkg;
  --
  file:///home/brent/Projects/merchstack/experiments/bootstrap-dev/reaction/node_modules/@reactioncommerce/api-plugin-authentication/src/util/accountServer.js:2
  import { Mongo } from "@accounts/mongo";
           ^^^^^
  SyntaxError: The requested module '@accounts/mongo' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
  For example:
  import pkg from '@accounts/mongo';
  const { Mongo } = pkg;
      at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
      at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
      at async Loader.import (internal/modules/esm/loader.js:165:24)
      at async importPluginsJSONFile (file:///home/brent/Projects/merchstack/experiments/bootstrap-dev/reaction/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js:44:30)
      at async runApp (file:///home/brent/Projects/merchstack/experiments/bootstrap-dev/reaction/src/index.js:15:19)

```

## Steps to Reproduce
1. Clone reaction
1. nvm use (to use Node 14)
1. npm install
1. `npm run start`
1. Observe the error

### Versions
4.1.5

**Comment by brent-hoover** [comment]
Updating to Node 14.18 resolves this issue, closing
