### ISSUE TITLE
Unable to translate schema labels

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#663]
I'm trying to translate schema labels, such as Price, Weight and others:
```
--- a/packages/reaction-schemas/common/schemas/products.js
+++ b/packages/reaction-schemas/common/schemas/products.js
@@ -171,7 +171,7 @@ ReactionCore.Schemas.ProductVariant = new SimpleSchema({
     }
   },
   price: {
-    label: "Price",
+    label: i18n.t("productDetailEdit.label.price", "Price"),
     type: Number,
     decimal: true,
     min: 0,
```
I'm getting error 

```
/Users/ramusus/.meteor/packages/meteor-tool/.1.1.10.1k87647++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
ReferenceError: i18n is not defined
    at ReactionCore.Schemas.Tag.SimpleSchema._id.type (common/schemas/products.js:174:12)
    at /Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/packages/reactioncommerce_reaction-schemas.js:2012:4
    at /Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/packages/reactioncommerce_reaction-schemas.js:2461:3
    at /Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/boot.js:242:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/ramusus/.meteor/packages/meteor-tool/.1.1.10.1k87647++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/boot.js:137:5
Exited with code: 8
Your application is crashing. Waiting for file change.
```

How should I define **i18n** variable inside this file?

**Comment by zenweasel** [comment]
@ramusus Hey Boris, I'm unclear on what you are trying to accomplish here. Can you help me understand? Are you still having this issue in v12 (development)?

**Comment by ramusus** [comment]
@zenweasel , It's very outdated issue, closing it
