### ISSUE TITLE
Cannot register a new user

### ISSUE THREAD

**Issue by zenweasel** [reactioncommerce/reaction#677]
Using most current code (clean clone) I get the following error when I try to register a user:
```Exception in onLogin callback: TypeError: Cannot read property '_id' of undefined
    at Meteor.methods.accounts/currentUserHasPassword.user (server/methods/accounts.js:109:39)
    at runAndHandleExceptions (packages/callback-hook/hook.js:133:1)```

**Comment by aaronjudd** [comment]
Clear cache,  that should fix.  see if we can find steps to replicate.
