### ISSUE TITLE
Failed to initialize a MongoDB replica set.

### ISSUE THREAD

**Issue by Imtiyaz94** [reactioncommerce/reaction#6837]
**While starting my fresh project using `reaction develop` . It is not starting instead showing error**

`Failed to initialize a MongoDB replica set. This may result in errors or some things not working. Error: Error checking replica set config: not running with --replSet (NoReplicationEnabled)` 

`MongoError: The $changeStream stage is only supported on replica sets
    at MessageStream.messageHandler (/home/dev/Desktop/Office/demo projects/Reaction Ecommerce/project1/server/node_modules/mongodb/lib/cmap/connection.js:268:20)
    at MessageStream.emit (events.js:400:28)
    at MessageStream.emit (domain.js:475:12)
    at processIncomingData (/home/dev/Desktop/Office/demo projects/Reaction Ecommerce/project1/server/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
    at MessageStream._write (/home/dev/Desktop/Office/demo projects/Reaction Ecommerce/project1/server/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at MessageStream.Writable.write (internal/streams/writable.js:303:10)
    at Socket.ondata (internal/streams/readable.js:731:22)
    at Socket.emit (events.js:400:28)
    at Socket.emit (domain.js:475:12) {
  ok: 0,
  code: 40573,
  codeName: 'Location40573'
}
`
**Is there anyone got issue?**

**Comment by fetrarij** [comment]
I think you have already running your mongodb server without the replica set config.
I have encoutered the same probleme because I already have mongodb installed on my system (without replica set) , and the app will always use that, so my solution was to stop it first before running reaction api.
