### ISSUE TITLE
After Meteor.call('flushTranslations') server don't want recreate translations and restart

### ISSUE THREAD

**Issue by ramusus** [reactioncommerce/reaction#806]
When I call 
    
    Meteor.call('flushTranslations')

from the client I've got error 

    Exception while invoking method 'flushTranslations' Error: Unknown asset: private/data/i18n/ar.json

And server don't want to restart automatically. But after start server manually it works fine.

Error traceback:

```
Exception while invoking method 'flushTranslations' Error: Unknown asset: private/data/i18n/ar.json
    at Object.Future.wait (/Users/ramusus/.meteor/packages/meteor-tool/.1.1.10.1k87647++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
    at getAsset (/Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/boot.js:212:20)
    at Object.Assets.getText (/Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/boot.js:217:16)
    at [object Object].Meteor.methods.flushTranslations (server/methods/shop.js:521:27)
    at packages/check/match.js:103:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:102:1)
    at maybeAuditArgumentChecks (livedata_server.js:1695:18)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
    at new Promise (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
    at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
    at livedata_server.js:548:43
    - - - - -
    at getAsset (/Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/boot.js:206:19)
    at Object.Assets.getText (/Users/ramusus/workspace/swap_meet/.meteor/local/build/programs/server/boot.js:217:16)
    at [object Object].Meteor.methods.flushTranslations (server/methods/shop.js:521:27)
    at packages/check/match.js:103:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:102:1)
    at maybeAuditArgumentChecks (livedata_server.js:1695:18)
    at livedata_server.js:708:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:706:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at livedata_server.js:704:46
    at tryCallTwo (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
    at new Promise (/Users/ramusus/.meteor/packages/promise/.0.5.1.vuovhs++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
    at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
    at livedata_server.js:548:43
```

**Comment by aaronjudd** [comment]
This is resolve in v0.12,  you do have to reload after flushing...
