### ISSUE TITLE
MongoError: exception: _id index cannot be non-unique

### ISSUE THREAD

**Issue by ScyDev** [reactioncommerce/reaction#865]
Happens during startup of reaction command with latest development changes from today.

```
/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
						throw(ex);
						      ^
MongoError: exception: _id index cannot be non-unique
    at Object.Future.wait (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
    at packages/aldeed_schema-index/lib/indexing.js:17:1
    at /var/www/src/.meteor/local/build/programs/server/boot.js:249:5
    - - - - -
    at Object.toError (/root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1354:26
    at Server.Base._callHandler (/root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/root/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
=> Exited with code: 8
```

**Comment by aaronjudd** [comment]
What are the steps to reproduce?

Do you have custom data that you are importing in the fixtures?  Is this  a fresh data reset?

**Comment by ScyDev** [comment]
1. switch my HEAD to latest commit on development
2. docker build .
3. run the docker image
4. reaction reset
5. reaction

So, it happens with a freshly built docker image with an empty db.

**Comment by ScyDev** [comment]
I stepped through the repo history.

The problem first appears with this commit: 
e02a24417a18044fd18f99b878a2cd3dcdd1f847 "- reaction-catalog - added missing files"

**Comment by aaronjudd** [comment]
on docker, is that a local db or a remote that you are using?  I'm curious because 12.0 and that commit introduced a new product schema, which is not compatible with the previous product schema, so if you are pointing at an existing data set, this is probably the issue.  You say though, that you did `reaction reset` which should mean a default structures, which I'd expect to be working fine (as we'd all be seeing this 100 times a day it that was broken).

**Comment by ScyDev** [comment]
It's a local db inside the container which was freshly built. I don't have a separate container for mongo.

**Comment by ScyDev** [comment]
Instead of just switching HEAD to development, I just did a new git clone of https://github.com/reactioncommerce/reaction and still get the same problem.

On Ubuntu 14.04 btw.

1. git clone https://github.com/reactioncommerce/reaction reaction-HEAD
2. cd reaction-HEAD
3. docker build .
Successfully built c2e18b3405e1
4. docker run -ti -p 3000:80 c2e18b3405e1
5.
```
MongoError: exception: _id index cannot be non-unique
    at Object.Future.wait (/var/www/bundle/programs/server/node_modules/fibers/future.js:398:15)
    at [object Object].MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:790:1)
    at packages/aldeed_schema-index/lib/indexing.js:17:1
    at /var/www/bundle/programs/server/boot.js:249:5
    - - - - -
    at Object.toError (/var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/db.js:1354:26
    at Server.Base._callHandler (/var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:488:18
    at [object Object].MongoReply.parseBody (/var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:446:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/var/www/bundle/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:440:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)

```

**Comment by aaronjudd** [comment]
@jshimko Any thoughts on this?

**Comment by jshimko** [comment]
Well, it appears to be something to do with using the Mongo driver to ensure indexes (which is implemented by [`aldeed:schema-index`](https://atmospherejs.com/aldeed/schema-index)).  If I remove `index: 1` from all of the schemas, the problem goes away.  HOWEVER, then a new unrelated issue pops up...
```
Error: Roles error: Can't mix grouped and non-grouped roles for same user
    at Object._.extend._updateUserRoles (packages/alanning_roles/roles_common.js:687:1)
    at Object._.extend.setUserRoles (packages/alanning_roles/roles_common.js:174:1)
    at Object.ReactionRegistry.createDefaultAdminUser (server/registry/defaultAdmin.js:105:9)
    at Object._.extend.init (server/main.js:23:22)
    at _.extend.init (server/init.js:7:16)
    at /var/www/bundle/programs/server/boot.js:249:5
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by jshimko** [comment]
Which is from this...

https://github.com/reactioncommerce/reaction/blob/development/packages/reaction-core/server/registry/defaultAdmin.js#L105

**Comment by jshimko** [comment]
Forgot to mention... that Mongo issue happens when Mongo is inside or outside the app container.

**Comment by jshimko** [comment]
This is kind of redundant anyway, no?

```js
// reaction-core/server/registry/defaultAdmin.js lines 102-105

  // we don't use accounts/addUserPermissions here because we may not yet have permissions
  Roles.setUserRoles(accountId, _.uniq(defaultAdminRoles), shopId);
  // // the reaction owner has permissions to all sites by default
  Roles.setUserRoles(accountId, _.uniq(defaultAdminRoles), Roles.GLOBAL_GROUP);
```

The second `setUserRoles` adds them to the global group (which technically accomplishes the same thing as scoping them to shopId)

**Comment by aaronjudd** [comment]
One is a "shop owner" role (shopId), .. one is the "installation owner" (global).  You can delete the shopOwner permissions in the admin, and then where would you be? an owner with no permissions. ;-)   Also making the assumption that shop owners in the future may not be able to add additional "owners" (they are admins).   You could just start with only the globals, but the the initial user wouldn't following the same format as future users.  In any case,  this is the functionality of roles and groups, and not specific to this user..  I'd expect that this behaviour works regardless of the necessity for this user.

**Comment by ScyDev** [comment]
I was able to resolve the `MongoError: exception: _id index cannot be non-unique` by changing all schemas to `index: 0` as @jshimko says above.

I've noticed that this remedy seems to have a permanent effect. I have since changed all schemas back to `index: 1` and it still works.

**Comment by jshimko** [comment]
@ScyDev You can also switch to using Mongo 2.x.  Neither scenario is ideal, so hopefully we can find a better option.  Perhaps Meteor's `_ensureIndex()`?
```js
MyCollection._ensureIndex({ "something": 1, "somethingElse": 1 });
```

**Comment by jshimko** [comment]
Also, the new Dockerfile I pushed out yesterday [gives you the ability to install specific Mongo versions now](https://github.com/reactioncommerce/reaction/blob/development/docker/reaction.dev.docker#L50-L53), so you can also do that if really want to have Mongo inside the app container.  Just set `INSTALL_MONGO` to `true` and build the image.

**Comment by ScyDev** [comment]
@jshimko Ok. But what still bothers me is that I am not using a custom version of Mongo, or changed anything else for that matter. Do I understand correctly that you also don't know what caused this problem? Your suggestions are very welcome, but they are only remedies to a problem we don't really understand, correct?

**Comment by jshimko** [comment]
As far as I can tell, the problem is because `aldeed:schema-index` uses a the Mongo driver for Node that in a way that isn't supported with Mongo 3.x.  And that's why using Mongo 2.x works (which is also what local development Meteor uses).  

I agree that having to use 2.x is not ideal.  My preference would be to remove that `aldeed:schema-index` package and use `Collection._ensureIndex` instead.  I've been using that for years with no issue (with both 2.x and 3.x versions of Mongo).

**Comment by ScyDev** [comment]
Ok, thanks for clarifying :)

**Comment by ScyDev** [comment]
@jshimko Yet another question: Does this make sense to you, that I only had to hange to `index: 0` temporarily, but after changing back to `index: 1` the "fix" is permanent and the problem is gone?

**Comment by jshimko** [comment]
You're using a 3.x version of Mongo now?

**Comment by aaronjudd** [comment]
https://docs.mongodb.org/ecosystem/drivers/node-js/#mongodb-compatibility
I think the issue isn’t 3.x but 3.2.x, 3.0 is what I was using previously in the  Docker builds.


Where I had previously `RUN echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main" | tee /etc/apt/sources.list.d/mongodb-org-3.0.list`

I was assuming that we were still running the 3.0 that I knew worked.. not 3.2 / latest.  so 3.0 works, but not 3.2 because of the node driver version, so it’s not aldeed:simple-schema issue, but rather Meteor / Node  mongo driver isn’t updated so we can go to 3.2.  **MongoDB  3.0 should be ok.**

**Comment by creaux** [comment]
@jshimko regarding your comment: https://github.com/reactioncommerce/reaction/issues/865#issuecomment-192681848

Regarding new unrelated issue. How to understand this. I trying to run Reaction Commerce on Heroku and I'm getting exactly this issue. When I running RC on local everything seems to be fine.

I getting this issue in case when I leaving all schema `index: 1`, what exactly causing this issue?

There has to be specific environment to get that so I'm bit confused about that.

**Comment by jshimko** [comment]
@creaux Can you please post the exact error you're getting so I can get a better idea of what's going on?  The original index error should be fixed, so I just want to make sure we're on the same page.

**Comment by creaux** [comment]
Here you go.

```
2016-03-25T15:55:16.371408+00:00 app[web.1]: /app/.meteor/heroku_build/app/programs/server/node_modules/fibers/future.js:278
2016-03-25T15:55:16.371758+00:00 app[web.1]:                                            throw(ex);
2016-03-25T15:55:16.371769+00:00 app[web.1]:                                                  ^
2016-03-25T15:55:16.758624+00:00 app[web.1]: Error: Roles error: Can't mix grouped and non-grouped roles for same user
2016-03-25T15:55:16.758634+00:00 app[web.1]:     at Object._.extend._updateUserRoles (packages/alanning_roles/roles_common.js:687:1)
2016-03-25T15:55:16.758634+00:00 app[web.1]:     at Object._.extend.addUsersToRoles (packages/alanning_roles/roles_common.js:145:1)
2016-03-25T15:55:16.758635+00:00 app[web.1]:     at Object.ReactionRegistry.assignOwnerRoles (server/registry/assignRoles.js:83:9)
2016-03-25T15:55:16.758636+00:00 app[web.1]:     at server/registry/loadPackages.js:38:24
2016-03-25T15:55:16.758637+00:00 app[web.1]:     at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1022:1)
2016-03-25T15:55:16.758638+00:00 app[web.1]:     at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:869:1)
2016-03-25T15:55:16.758638+00:00 app[web.1]:     at server/registry/loadPackages.js:33:50
2016-03-25T15:55:16.758639+00:00 app[web.1]:     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
2016-03-25T15:55:16.758640+00:00 app[web.1]:     at Object.ReactionRegistry.loadPackages (server/registry/loadPackages.js:32:5)
2016-03-25T15:55:16.758640+00:00 app[web.1]:     at Object._.extend.init (server/main.js:18:22)
2016-03-25T15:55:16.758641+00:00 app[web.1]:     at _.extend.init (server/init.js:7:16)
2016-03-25T15:55:16.758642+00:00 app[web.1]:     at /app/.meteor/heroku_build/app/programs/server/boot.js:249:5
2016-03-25T15:55:17.708776+00:00 heroku[web.1]: Process exited with status 8
```

**Comment by jshimko** [comment]
That's a known (and unrelated) issue that I believe is possibly because of a race condition with getting newly inserted data from the database.  I think it only happens when deployed because the database is usually further away (and has slightly more latency as a result).  We're working on a fix.  I'll reply here when it's sorted out.

**Comment by aaronjudd** [comment]
re roles error, see: https://github.com/alanning/meteor-roles/issues/185

**Comment by paul-bo** [comment]
got the same error while deploying to galaxy and remote db with mlab (version: 3.0.12)

I got the error because I was using `index: 1,` and `_ensureIndex()` on the same specified field. After removing the duplication on the same specified field I was still using both `index: 1,` and `_ensureIndex()` and the startup on galaxy went fine.

**Comment by aaronjudd** [comment]
@paul-bo thanks for that info. make sense.
